package Omtbs;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/* @author richu */

public class AdminRegister extends javax.swing.JFrame {

    /* Creates new form AdminRegister */
    public AdminRegister() {
        initComponents();
        this.HidePasswordIcon.setVisible(false);
        this.ConfirmHidePasswordIcon.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminRegistrationMainPanel = new javax.swing.JPanel();
        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        MaximizeButton = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        RoleLabel = new javax.swing.JLabel();
        CompanyLogo = new javax.swing.JLabel();
        EmailIdLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();
        AddressTextAreaScrollPane = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        PasswordField = new javax.swing.JPasswordField();
        AddressLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ShowPasswordIcon = new javax.swing.JButton();
        HidePasswordIcon = new javax.swing.JButton();
        ConfirmShowPasswordIcon = new javax.swing.JButton();
        ConfirmHidePasswordIcon = new javax.swing.JButton();
        EmailIdTextField = new javax.swing.JTextField();
        UserNameTextField = new javax.swing.JTextField();
        AdminRegistrationBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Registration");
        setLocationByPlatform(true);
        setName("AdminRegistrationFrame"); // NOI18N
        setUndecorated(true);

        AdminRegistrationMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdminRegistrationMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseButton.setText("4");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        AdminRegistrationMainPanel.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, 50, 50));

        MinimizeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeButton.setText("4");
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });
        AdminRegistrationMainPanel.add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 50, 50));

        MaximizeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        MaximizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeButton.setText("4");
        MaximizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeButtonMouseClicked(evt);
            }
        });
        AdminRegistrationMainPanel.add(MaximizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 50, -1));

        LoginButton.setBackground(new java.awt.Color(51, 255, 153));
        LoginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setBorderPainted(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        AdminRegistrationMainPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 660, 220, 50));

        RoleLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        RoleLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoleLabel.setText("ROLE:");
        AdminRegistrationMainPanel.add(RoleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 60, 50));

        CompanyLogo.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        CompanyLogo.setForeground(new java.awt.Color(255, 255, 255));
        CompanyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/lightning _50px.png"))); // NOI18N
        CompanyLogo.setText("ADMIN REGISTRATION ");
        CompanyLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        AdminRegistrationMainPanel.add(CompanyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 50));

        EmailIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setText("EMAIL ID:");
        AdminRegistrationMainPanel.add(EmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, 40));

        UserNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLabel.setText("USER NAME:");
        AdminRegistrationMainPanel.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 40));

        ConfirmPasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordLabel.setText("CONFIRM PASSWORD:");
        AdminRegistrationMainPanel.add(ConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 210, 40));

        PasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("PASSWORD:");
        AdminRegistrationMainPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 110, 40));

        RoleComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin" }));
        AdminRegistrationMainPanel.add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 200, 50));

        AddressTextArea.setColumns(20);
        AddressTextArea.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AddressTextArea.setRows(5);
        AddressTextAreaScrollPane.setViewportView(AddressTextArea);

        AdminRegistrationMainPanel.add(AddressTextAreaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 400, 230));

        ConfirmPasswordField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AdminRegistrationMainPanel.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 360, 40));

        PasswordField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AdminRegistrationMainPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 360, 40));

        AddressLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddressLabel.setText("ADDRESS:");
        AdminRegistrationMainPanel.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 90, 50));

        SubmitButton.setBackground(new java.awt.Color(255, 255, 0));
        SubmitButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.setBorderPainted(false);
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        AdminRegistrationMainPanel.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 230, 50));

        CancelButton.setBackground(new java.awt.Color(255, 102, 102));
        CancelButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorderPainted(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        AdminRegistrationMainPanel.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, 240, 50));

        ShowPasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setToolTipText("Show Password");
        ShowPasswordIcon.setBorder(null);
        ShowPasswordIcon.setBorderPainted(false);
        ShowPasswordIcon.setContentAreaFilled(false);
        ShowPasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setSelected(true);
        ShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowPasswordIconMousePressed(evt);
            }
        });
        AdminRegistrationMainPanel.add(ShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 40, 40));

        HidePasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        HidePasswordIcon.setToolTipText("Hide Password");
        HidePasswordIcon.setBorder(null);
        HidePasswordIcon.setBorderPainted(false);
        HidePasswordIcon.setContentAreaFilled(false);
        HidePasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HidePasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        HidePasswordIcon.setSelected(true);
        HidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HidePasswordIconMousePressed(evt);
            }
        });
        AdminRegistrationMainPanel.add(HidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 40, 40));

        ConfirmShowPasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConfirmShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmShowPasswordIcon.setToolTipText("Show Password");
        ConfirmShowPasswordIcon.setBorder(null);
        ConfirmShowPasswordIcon.setBorderPainted(false);
        ConfirmShowPasswordIcon.setContentAreaFilled(false);
        ConfirmShowPasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmShowPasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmShowPasswordIcon.setSelected(true);
        ConfirmShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmShowPasswordIconMousePressed(evt);
            }
        });
        AdminRegistrationMainPanel.add(ConfirmShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 40, 40));

        ConfirmHidePasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConfirmHidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        ConfirmHidePasswordIcon.setToolTipText("Hide Password");
        ConfirmHidePasswordIcon.setBorder(null);
        ConfirmHidePasswordIcon.setBorderPainted(false);
        ConfirmHidePasswordIcon.setContentAreaFilled(false);
        ConfirmHidePasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmHidePasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmHidePasswordIcon.setSelected(true);
        ConfirmHidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmHidePasswordIconMousePressed(evt);
            }
        });
        AdminRegistrationMainPanel.add(ConfirmHidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 40, 40));

        EmailIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AdminRegistrationMainPanel.add(EmailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 360, 40));

        UserNameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AdminRegistrationMainPanel.add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 360, 40));

        AdminRegistrationBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/william-daigneault_1450px.jpg"))); // NOI18N
        AdminRegistrationMainPanel.add(AdminRegistrationBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminRegistrationMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminRegistrationMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1450, 790));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void MaximizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeButtonMouseClicked
        if(this.getExtendedState()!= Login.MAXIMIZED_BOTH){
            this.setExtendedState(Login.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Login.NORMAL);
        }
    }//GEN-LAST:event_MaximizeButtonMouseClicked

    private void ShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordIconMousePressed
        HidePasswordIcon.setVisible(true);
        ShowPasswordIcon.setVisible(false);
        PasswordField.setEchoChar((char)0);
    }//GEN-LAST:event_ShowPasswordIconMousePressed

    private void HidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordIconMousePressed
        ShowPasswordIcon.setVisible(true);
        HidePasswordIcon.setVisible(false);
        PasswordField.setEchoChar('*');
    }//GEN-LAST:event_HidePasswordIconMousePressed

    private void ConfirmShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmShowPasswordIconMousePressed
        ConfirmHidePasswordIcon.setVisible(true);
        ConfirmShowPasswordIcon.setVisible(false);
        ConfirmPasswordField.setEchoChar((char)0);
    }//GEN-LAST:event_ConfirmShowPasswordIconMousePressed

    private void ConfirmHidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmHidePasswordIconMousePressed
        ConfirmShowPasswordIcon.setVisible(true);
        ConfirmHidePasswordIcon.setVisible(false);
        ConfirmPasswordField.setEchoChar('*');
    }//GEN-LAST:event_ConfirmHidePasswordIconMousePressed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String auname = UserNameTextField.getText();
        String auemailid = EmailIdTextField.getText();
        String aupassword = String.valueOf(PasswordField.getPassword());
        String aucpassword = String.valueOf(ConfirmPasswordField.getPassword());
        String auaddress = AddressTextArea.getText();
        String aurole = (String) RoleComboBox.getSelectedItem();
        
        String userregex = "^[a-zA-Z ]{0,29}$";
        Pattern userp = Pattern.compile(userregex);
        Matcher usermatch = userp.matcher(UserNameTextField.getText());
        
        String emailregex = "^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z" + "A-Z]{2,7}$";
        Pattern emailp = Pattern.compile(emailregex);
        Matcher emailidmatch = emailp.matcher(EmailIdTextField.getText());

        String passregex = "^[a-zA-Z0-9*-+@&#@!]{1,12}$";
        Pattern passp = Pattern.compile(passregex);
        Matcher passmatch = passp.matcher(String.valueOf(PasswordField.getPassword()));
        
        if(auname.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The User Name" , "User Name", JOptionPane.WARNING_MESSAGE);
        }
        else if(!usermatch.matches()){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The User Name In The User Name Format" , "User Name Format", JOptionPane.WARNING_MESSAGE);
        }
        else if(auemailid.equals("")){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Email id" , "Email Id", JOptionPane.WARNING_MESSAGE);
        }
        else if(!emailidmatch.matches()){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Email Id In The Email Id Format" , "Email Id Format", JOptionPane.WARNING_MESSAGE);
        }
        else if(aupassword.equals("")){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Password" , "Password", JOptionPane.WARNING_MESSAGE);
        }
        else if(!passmatch.matches()){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Password Above 7" , "Password Format", JOptionPane.WARNING_MESSAGE);
        }
        else if(aucpassword.equals("")){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Confirm Password" , "Confirm Password", JOptionPane.WARNING_MESSAGE);
        }
        else if(!aucpassword.equals(aupassword)){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Entered Confirm Password Does't Match" , "Does't Match", JOptionPane.WARNING_MESSAGE);
        }
        else if(auaddress.equals("")){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Address" , "Address", JOptionPane.WARNING_MESSAGE);
        }
        else if(aurole.equals("")){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Select The Role" , "Role", JOptionPane.WARNING_MESSAGE);
        }
        else {
            PreparedStatement ps;
            String RegisterUserQuery = "INSERT INTO `admin`(`ADMIN_NAME`, `ADMIN_EMAIL_ID`, `ADMIN_PASSWORD`, `ADMIN_ADDRESS`, `ROLE`) VALUES (?,?,?,?,?)";
            try{
            ps = MyConnection.getConnection().prepareStatement(RegisterUserQuery);
            ps.setString(1, auname);
            ps.setString(2, auemailid);
            ps.setString(3, aupassword);
            ps.setString(4, auaddress);
            ps.setString(5, aurole);            
                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null,"Admin Account Successfully Created" , "Admin Account", JOptionPane.INFORMATION_MESSAGE);
                    AdminLogin nal = new AdminLogin();
                    nal.setVisible(true);
                    nal.pack();
                    nal.setLocationRelativeTo(null);
                    nal.setExtendedState(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
                else{
                     Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null,"DataBase Insertion Failed!" , "Database Connection", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            catch (SQLException ex) {
                Logger.getLogger(AdminRegister.class.getName()).log(Level.SEVERE, null, ex);
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,"Mysql Connection Error Occuring!" , "Mysql Error Message", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        AdminRegisterMail arm = new AdminRegisterMail();
        arm.setVisible(true);
        arm.pack();
        arm.setLocationRelativeTo(null);
        arm.setExtendedState(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        AdminLogin nal = new AdminLogin();
        nal.setVisible(true);
        nal.pack();
        nal.setLocationRelativeTo(null);
        nal.setExtendedState(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JScrollPane AddressTextAreaScrollPane;
    private javax.swing.JLabel AdminRegistrationBgImg;
    private javax.swing.JPanel AdminRegistrationMainPanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JLabel CompanyLogo;
    private javax.swing.JButton ConfirmHidePasswordIcon;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JButton ConfirmShowPasswordIcon;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JTextField EmailIdTextField;
    private javax.swing.JButton HidePasswordIcon;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel MaximizeButton;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JButton ShowPasswordIcon;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    // End of variables declaration//GEN-END:variables
}
