package Omtbs;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/* @author richu */

public class ForgetPassword extends javax.swing.JFrame {
    
    String from,to,host,sub;
    int content;
    public  int ResetPassOtp;  
    public static String ResetPassUserName; 
    String newline = System.lineSeparator();
    
    /* Creates new form ForgetPassword */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgetMainPanel = new javax.swing.JPanel();
        GoBackButton = new javax.swing.JButton();
        MinimizeIcon = new javax.swing.JLabel();
        ForgetPasswordImg = new javax.swing.JLabel();
        FPUsernameLabel = new javax.swing.JLabel();
        FPTextUser = new javax.swing.JTextField();
        FPEmailIdLabel = new javax.swing.JLabel();
        FPTextEmailId = new javax.swing.JTextField();
        FPOTPLabel = new javax.swing.JLabel();
        FPTextOtp = new javax.swing.JTextField();
        SentButton = new javax.swing.JButton();
        FPVerifyCodeButton = new javax.swing.JButton();
        FPResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forget Password");
        setLocationByPlatform(true);
        setName("ForgetPasswordFrame"); // NOI18N
        setUndecorated(true);

        ForgetMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        ForgetMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GoBackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        GoBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Previous_50px.png"))); // NOI18N
        GoBackButton.setText("Go Back");
        GoBackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GoBackButton.setBorderPainted(false);
        GoBackButton.setContentAreaFilled(false);
        GoBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });
        ForgetMainPanel.add(GoBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        MinimizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeIconMouseClicked(evt);
            }
        });
        ForgetMainPanel.add(MinimizeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 50));

        ForgetPasswordImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Forgot_180px.png"))); // NOI18N
        ForgetMainPanel.add(ForgetPasswordImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 180, 190));

        FPUsernameLabel.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        FPUsernameLabel.setText("Username:");
        ForgetMainPanel.add(FPUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 40));

        FPTextUser.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ForgetMainPanel.add(FPTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 360, 40));

        FPEmailIdLabel.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        FPEmailIdLabel.setText("Email Id:");
        ForgetMainPanel.add(FPEmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 40));

        FPTextEmailId.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ForgetMainPanel.add(FPTextEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 360, 40));

        FPOTPLabel.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        FPOTPLabel.setText("Enter OTP:");
        ForgetMainPanel.add(FPOTPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, 40));

        FPTextOtp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ForgetMainPanel.add(FPTextOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 360, 40));

        SentButton.setBackground(new java.awt.Color(51, 255, 51));
        SentButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        SentButton.setText("Sent");
        SentButton.setBorder(null);
        SentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SentButtonActionPerformed(evt);
            }
        });
        ForgetMainPanel.add(SentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 210, 50));

        FPVerifyCodeButton.setBackground(new java.awt.Color(255, 51, 102));
        FPVerifyCodeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        FPVerifyCodeButton.setForeground(new java.awt.Color(255, 255, 255));
        FPVerifyCodeButton.setText("Verify Code");
        FPVerifyCodeButton.setBorder(null);
        FPVerifyCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPVerifyCodeButtonActionPerformed(evt);
            }
        });
        ForgetMainPanel.add(FPVerifyCodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 220, 50));

        FPResetButton.setBackground(new java.awt.Color(255, 51, 102));
        FPResetButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        FPResetButton.setForeground(new java.awt.Color(255, 255, 255));
        FPResetButton.setText("Reset");
        FPResetButton.setBorder(null);
        FPResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPResetButtonActionPerformed(evt);
            }
        });
        ForgetMainPanel.add(FPResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ForgetMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ForgetMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(745, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeIconMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeIconMouseClicked

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
       Login log = new Login();
       log.setVisible(true);
       log.pack();
       log.setLocationRelativeTo(null);
       log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void FPVerifyCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPVerifyCodeButtonActionPerformed
        String enterOtp = FPTextOtp.getText();
        if(enterOtp.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please Enter OTP", "OTP Message", JOptionPane.WARNING_MESSAGE);
        }
        else if(Integer.valueOf(FPTextOtp.getText()) == ResetPassOtp){          
            ResetPassword rp = new ResetPassword();
            rp.setVisible(true);
            rp.pack();
            rp.setLocationRelativeTo(null);
            rp.setExtendedState(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        else{
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Invalid Otp!", "OTP Message.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FPVerifyCodeButtonActionPerformed

    private void FPResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPResetButtonActionPerformed
       FPTextUser.setText("");
       FPTextEmailId.setText("");
       FPTextOtp.setText("");
    }//GEN-LAST:event_FPResetButtonActionPerformed

    private void SentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SentButtonActionPerformed
        String UserName = FPTextUser.getText();
        String UserEmail = FPTextEmailId.getText();
        if(UserName.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Provided User Name" , "User Name", JOptionPane.WARNING_MESSAGE);
        }
        else if(UserEmail.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter The Provided Email id" , "Email Id", JOptionPane.WARNING_MESSAGE);
        } 
        else{
            try {
                PreparedStatement ps;
                ResultSet rs;
                String ForgetPassquery = "SELECT * FROM `user` WHERE `USER_NAME` = ? AND `USER_EMAILID` = ?"; 
                ps = MyConnection.getConnection().prepareStatement(ForgetPassquery);
                ps.setString(1, UserName);
                ps.setString(2, UserEmail);
                rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Verification Of Existing User; Existing User" , "Existing User Message", JOptionPane.INFORMATION_MESSAGE);
                    ResetPassUserName = FPTextUser.getText();  
                    try {
                        ResetPassOtp = generateOtp();
                        System.out.print(ResetPassOtp);
                        System.out.print(newline);
                        PreparedStatement psn;
                        ResultSet rsn;
                        String RPassquery = "SELECT USER_EMAILID FROM `user` WHERE `USER_NAME` = ?"; 
                        psn = MyConnection.getConnection().prepareStatement(RPassquery);
                        psn.setString(1, UserName);
                        rsn = psn.executeQuery();
                        if(rsn.next()){
                            JOptionPane.showMessageDialog(null,"Mail Address Verification Successfully" , "Mail verification Message", JOptionPane.INFORMATION_MESSAGE);
                                     
                            from = "omtbs1818@gmail.com";
                            to = FPTextEmailId.getText();
                            host = "localhost";
                            sub = "VERIFY OTP";
                            content = ResetPassOtp;
                            Properties p = new Properties();
                            p.put("mail.smtp.auth", "true");
                            p.put("mail.starttls.enable", "true");
                            p.put("mail.smtp.host", "smtp.gmail.com");
                            p.put("mail.smtp.port", "465");
                            p.put("mail.smtp.socketFactory.port", "465");    
                            p.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                            Session s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
                            protected PasswordAuthentication getPasswordAuthentication(){
                                 return new PasswordAuthentication("omtbs1818@gmail.com","Omtbs@123456789");
                            }
                            });
                            try
                            {
                               MimeMessage m = new MimeMessage(s);
                               m.setFrom(from);
                               m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                               m.setSubject(sub);
                               m.setText(Integer.toString(content)); 
                               Transport.send(m);
                               System.out.println("success");
                               JOptionPane.showMessageDialog(null, "OTP Is Successfully Send To The Email Address.", "Verification OTP Message", JOptionPane.INFORMATION_MESSAGE);
                               FPTextOtp.requestFocus();
                            }
                            catch(Exception e)
                            {
                               e.printStackTrace();
                            }
                        } 
                    } catch(SQLException ex){
                       Logger.getLogger(ForgetPassword.class.getName()).log(Level.SEVERE, null, ex);
                       Toolkit.getDefaultToolkit().beep();
                       JOptionPane.showMessageDialog(null,"Mail Address Fetch Unsuccessfully!" , "Mail Fetch Error!", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null,"User Account Not Be Created! Or Not Found!" , "User Login Error Message", JOptionPane.INFORMATION_MESSAGE);
                    FPTextUser.setText("");
                    FPTextEmailId.setText("");
                }
            } catch(SQLException ex){
                       Logger.getLogger(ForgetPassword.class.getName()).log(Level.SEVERE, null, ex);
                       JOptionPane.showMessageDialog(null,"Not An Existing User!" , "User Existance Error", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_SentButtonActionPerformed

    private static int generateOtp(){
       int otp = (int) (Math.random()*1000000); 
       return otp;
    }
    
    /* @param args the command line arguments */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FPEmailIdLabel;
    private javax.swing.JLabel FPOTPLabel;
    private javax.swing.JButton FPResetButton;
    private javax.swing.JTextField FPTextEmailId;
    private javax.swing.JTextField FPTextOtp;
    private javax.swing.JTextField FPTextUser;
    private javax.swing.JLabel FPUsernameLabel;
    private javax.swing.JButton FPVerifyCodeButton;
    private javax.swing.JPanel ForgetMainPanel;
    private javax.swing.JLabel ForgetPasswordImg;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel MinimizeIcon;
    private javax.swing.JButton SentButton;
    // End of variables declaration//GEN-END:variables
}
