package Omtbs;

import javax.swing.JOptionPane;

/* @author richu */

public class LoadingWindow extends javax.swing.JFrame {

    /* Creates new form LodingScreen */
    public LoadingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingWindowPanel = new javax.swing.JPanel();
        CompanyLogoIcon = new javax.swing.JLabel();
        OmtbsLabel = new javax.swing.JLabel();
        PopcornImg = new javax.swing.JLabel();
        CompanyNameLabel = new javax.swing.JLabel();
        CloseIcon = new javax.swing.JLabel();
        MinimizeIcon = new javax.swing.JLabel();
        MaximizeIcon = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        FilmImg = new javax.swing.JLabel();
        MovieCutImg = new javax.swing.JLabel();
        EmailIdLabel = new javax.swing.JLabel();
        WhatsappNoLabel = new javax.swing.JLabel();
        LoadingWindowBgImg = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OMTBS");
        setFocusableWindowState(false);
        setLocationByPlatform(true);
        setName("LoadingWindowFrame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        LoadingWindowPanel.setBackground(new java.awt.Color(0, 153, 255));
        LoadingWindowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompanyLogoIcon.setBackground(new java.awt.Color(255, 255, 255));
        CompanyLogoIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        CompanyLogoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompanyLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/lightning _50px.png"))); // NOI18N
        CompanyLogoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompanyLogoIcon.setIconTextGap(10);
        LoadingWindowPanel.add(CompanyLogoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        OmtbsLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        OmtbsLabel.setForeground(new java.awt.Color(102, 102, 255));
        OmtbsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OmtbsLabel.setText("Online Movie Ticket Booking System");
        LoadingWindowPanel.add(OmtbsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 630, 50));

        PopcornImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/movie-ticket_300px.png"))); // NOI18N
        LoadingWindowPanel.add(PopcornImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 300, -1));

        CompanyNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        CompanyNameLabel.setForeground(new java.awt.Color(255, 102, 0));
        CompanyNameLabel.setText("RA Private Lmt.");
        CompanyNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadingWindowPanel.add(CompanyNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 250, 40));

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseIconMouseClicked(evt);
            }
        });
        LoadingWindowPanel.add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 50, 50));

        MinimizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeIconMouseClicked(evt);
            }
        });
        LoadingWindowPanel.add(MinimizeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 50, 50));

        MaximizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeIcon.setText("jLabel1");
        MaximizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaximizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeIconMouseClicked(evt);
            }
        });
        LoadingWindowPanel.add(MaximizeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 50, 50));

        LoadingLabel.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 51, 51));
        LoadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoadingLabel.setText("Loading...");
        LoadingLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        LoadingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LoadingWindowPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 410, 40));

        LoadingValue.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 102, 51));
        LoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoadingValue.setText("0%");
        LoadingValue.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        LoadingWindowPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 720, 70, 40));

        FilmImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Filml_200px.png"))); // NOI18N
        FilmImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadingWindowPanel.add(FilmImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 600, 210, 122));

        MovieCutImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/film-clipart_200px.png"))); // NOI18N
        MovieCutImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadingWindowPanel.add(MovieCutImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, 140));

        EmailIdLabel.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(102, 102, 102));
        EmailIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Gmail_32px.png"))); // NOI18N
        EmailIdLabel.setText("omtbs1818@gmail.com");
        EmailIdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EmailIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        LoadingWindowPanel.add(EmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 170, 40));

        WhatsappNoLabel.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        WhatsappNoLabel.setForeground(new java.awt.Color(102, 102, 102));
        WhatsappNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WhatsappNoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/whatsapp_30px.png"))); // NOI18N
        WhatsappNoLabel.setText("9856128589");
        WhatsappNoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WhatsappNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        LoadingWindowPanel.add(WhatsappNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, 120, 40));

        LoadingWindowBgImg.setForeground(new java.awt.Color(51, 255, 102));
        LoadingWindowBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Movie_wallpaper_1306px.jpg"))); // NOI18N
        LoadingWindowPanel.add(LoadingWindowBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        getContentPane().add(LoadingWindowPanel);
        LoadingWindowPanel.setBounds(0, 0, 1310, 760);

        LoadingBar.setBackground(new java.awt.Color(255, 255, 255));
        LoadingBar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LoadingBar.setForeground(new java.awt.Color(0, 255, 51));
        LoadingBar.setToolTipText("");
        LoadingBar.setBorderPainted(false);
        LoadingBar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(LoadingBar);
        LoadingBar.setBounds(-10, 750, 1320, 30);

        setSize(new java.awt.Dimension(1306, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeIconMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_MinimizeIconMouseClicked

    private void CloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseIconMouseClicked

    private void MaximizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeIconMouseClicked
        if(this.getExtendedState()!= LoadingWindow.MAXIMIZED_BOTH){
            this.setExtendedState(LoadingWindow.MAXIMIZED_BOTH);       
        }
        else{
            this.setExtendedState(LoadingWindow.NORMAL);
        }
    }//GEN-LAST:event_MaximizeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //System.out.println(info.getClassName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  System.out.println(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        LoadingWindow ls = new LoadingWindow();
        ls.setVisible(true);
        Login log =new Login();
        try{
            for (int i=0;i<=100;i++) {
                int SleepTime = 100;
                Thread.sleep(SleepTime);
                ls.LoadingValue.setText(i + "%");
                ls.LoadingBar.setValue(i);
                if (i==10) {
                    ls.LoadingLabel.setText("Prepraing Modules...");
                }
                if (i==20) {
                    ls.LoadingLabel.setText("Turning on Modules...");
                }
                if (i==30) {
                    ls.LoadingLabel.setText("Loading Modules...");
                }
                if (i==50) {
                    ls.LoadingLabel.setText("Connecting to Server...");
                }
                if (i==70) {
                    ls.LoadingLabel.setText("Connection Established!");
                }
                if (i==80) {
                    ls.LoadingLabel.setText("Preparation For Lauanching...");
                }
                if (i==90) {
                    ls.LoadingLabel.setText("Launching Application...");
                }  
                if (i==100) {
                    boolean flase = false;
                    ls.setVisible(flase);
                    ls.dispose();
                }
            }
        }
        catch(InterruptedException e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"System Is Crashing" , "Error Message", JOptionPane.ERROR_MESSAGE);
        }
         log.setVisible(true);
         ls.dispose();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseIcon;
    private javax.swing.JLabel CompanyLogoIcon;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JLabel FilmImg;
    public javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    public javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel LoadingWindowBgImg;
    private javax.swing.JPanel LoadingWindowPanel;
    private javax.swing.JLabel MaximizeIcon;
    private javax.swing.JLabel MinimizeIcon;
    private javax.swing.JLabel MovieCutImg;
    private javax.swing.JLabel OmtbsLabel;
    private javax.swing.JLabel PopcornImg;
    private javax.swing.JLabel WhatsappNoLabel;
    // End of variables declaration//GEN-END:variables
}
