package Omtbs;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/* @author richu */

public class Login extends javax.swing.JFrame {

    /* Creates new form Login */
    public Login() {
        initComponents();
        this.HidePasswordIcon.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        CompanyLogoIcon = new javax.swing.JLabel();
        UserLoginFormLabel = new javax.swing.JLabel();
        CloseButtonIcon = new javax.swing.JButton();
        MinimizeButtonIcon = new javax.swing.JButton();
        MaximizeButtonIcon = new javax.swing.JButton();
        LoginSwitchUserIcon = new javax.swing.JLabel();
        UserUserNameLabel = new javax.swing.JLabel();
        UserUserNameIcon = new javax.swing.JLabel();
        UserUserNameTextField = new javax.swing.JTextField();
        UserPasswordLabel = new javax.swing.JLabel();
        UserPasswordIcon = new javax.swing.JLabel();
        UserPasswordPassField = new javax.swing.JPasswordField();
        ShowPasswordIcon = new javax.swing.JButton();
        HidePasswordIcon = new javax.swing.JButton();
        EmailIdName = new javax.swing.JLabel();
        UserEmailIdIcon = new javax.swing.JLabel();
        UserEmailIdTextField = new javax.swing.JTextField();
        UserPrivacyPolicyLabel = new javax.swing.JLabel();
        UserPrivacyPolicyIcon = new javax.swing.JLabel();
        UserAgreeCheckBox = new javax.swing.JCheckBox();
        UserSignInButton = new javax.swing.JButton();
        UserSignUpButton = new javax.swing.JButton();
        UserNoteLabel = new javax.swing.JLabel();
        UserForgetLabel = new javax.swing.JLabel();
        PrivacyIcon = new javax.swing.JButton();
        StayConnectWithUsLabel = new javax.swing.JLabel();
        SecurityIcon = new javax.swing.JButton();
        UserLoginBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Login");
        setLocationByPlatform(true);
        setName("LoginFrame"); // NOI18N
        setUndecorated(true);

        LoginPanel.setBackground(new java.awt.Color(255, 255, 153));
        LoginPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginPanel.setPreferredSize(new java.awt.Dimension(1230, 820));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompanyLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/lightning _50px.png"))); // NOI18N
        CompanyLogoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginPanel.add(CompanyLogoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        UserLoginFormLabel.setFont(new java.awt.Font("Unispace", 3, 33)); // NOI18N
        UserLoginFormLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLoginFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLoginFormLabel.setText("USER LOGIN ");
        UserLoginFormLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LoginPanel.add(UserLoginFormLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, 60));

        CloseButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseButtonIcon.setBorderPainted(false);
        CloseButtonIcon.setContentAreaFilled(false);
        CloseButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButtonIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonIconMouseClicked(evt);
            }
        });
        LoginPanel.add(CloseButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 50, 50));

        MinimizeButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MinimizeButtonIcon.setBorderPainted(false);
        MinimizeButtonIcon.setContentAreaFilled(false);
        MinimizeButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButtonIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonIconMouseClicked(evt);
            }
        });
        LoginPanel.add(MinimizeButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 50, 50));

        MaximizeButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MaximizeButtonIcon.setBorderPainted(false);
        MaximizeButtonIcon.setContentAreaFilled(false);
        MaximizeButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaximizeButtonIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeButtonIconMouseClicked(evt);
            }
        });
        LoginPanel.add(MaximizeButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 50, 50));

        LoginSwitchUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/switches_50px.png"))); // NOI18N
        LoginSwitchUserIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginSwitchUserIconMouseClicked(evt);
            }
        });
        LoginPanel.add(LoginSwitchUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, 50));

        UserUserNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserUserNameLabel.setText("User Name:");
        LoginPanel.add(UserUserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        UserUserNameIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserUserNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Customer_50px.png"))); // NOI18N
        UserUserNameIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginPanel.add(UserUserNameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 50, 50));

        UserUserNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        UserUserNameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserUserNameTextField.setToolTipText("User name contain only alphabets");
        UserUserNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        LoginPanel.add(UserUserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 340, 40));

        UserPasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserPasswordLabel.setText("Password:");
        LoginPanel.add(UserPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 110, -1));

        UserPasswordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/key_50px.png"))); // NOI18N
        LoginPanel.add(UserPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 50, 50));

        UserPasswordPassField.setBackground(new java.awt.Color(204, 204, 204));
        UserPasswordPassField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserPasswordPassField.setToolTipText("Password must contain at least 8 characters with (Captial letters, Small letters, Numbers, Special Charcters @ ! # $ % & * - + )");
        UserPasswordPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        LoginPanel.add(UserPasswordPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 340, 40));

        ShowPasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setToolTipText("Show Password");
        ShowPasswordIcon.setBorder(null);
        ShowPasswordIcon.setBorderPainted(false);
        ShowPasswordIcon.setContentAreaFilled(false);
        ShowPasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setSelected(true);
        ShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowPasswordIconMousePressed(evt);
            }
        });
        LoginPanel.add(ShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 40, 40));

        HidePasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        HidePasswordIcon.setToolTipText("Hide Password");
        HidePasswordIcon.setBorder(null);
        HidePasswordIcon.setBorderPainted(false);
        HidePasswordIcon.setContentAreaFilled(false);
        HidePasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HidePasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        HidePasswordIcon.setSelected(true);
        HidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HidePasswordIconMousePressed(evt);
            }
        });
        LoginPanel.add(HidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 40, -1));

        EmailIdName.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        EmailIdName.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdName.setText("Email ID:");
        LoginPanel.add(EmailIdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 90, -1));

        UserEmailIdIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserEmailIdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Emailn_50px.png"))); // NOI18N
        UserEmailIdIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginPanel.add(UserEmailIdIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 50, 50));

        UserEmailIdTextField.setBackground(new java.awt.Color(204, 204, 204));
        UserEmailIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserEmailIdTextField.setToolTipText("Email Id");
        UserEmailIdTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        LoginPanel.add(UserEmailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 340, 40));

        UserPrivacyPolicyLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserPrivacyPolicyLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserPrivacyPolicyLabel.setText("Privacy Policy:");
        LoginPanel.add(UserPrivacyPolicyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 150, 30));

        UserPrivacyPolicyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserPrivacyPolicyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Secure_50px.png"))); // NOI18N
        LoginPanel.add(UserPrivacyPolicyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 50, 50));

        UserAgreeCheckBox.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserAgreeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        UserAgreeCheckBox.setSelected(true);
        UserAgreeCheckBox.setText("   AGREE");
        UserAgreeCheckBox.setContentAreaFilled(false);
        UserAgreeCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginPanel.add(UserAgreeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 150, 50));

        UserSignInButton.setBackground(new java.awt.Color(102, 255, 102));
        UserSignInButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        UserSignInButton.setForeground(new java.awt.Color(255, 255, 255));
        UserSignInButton.setText("Sign In");
        UserSignInButton.setBorder(null);
        UserSignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserSignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSignInButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(UserSignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 270, 50));

        UserSignUpButton.setBackground(new java.awt.Color(255, 102, 51));
        UserSignUpButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        UserSignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        UserSignUpButton.setText("Sign Up");
        UserSignUpButton.setBorder(null);
        UserSignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserSignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserSignUpButtonMouseClicked(evt);
            }
        });
        LoginPanel.add(UserSignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 290, 50));

        UserNoteLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        UserNoteLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserNoteLabel.setText("NOTE: If You Are A New User, Please Sign Up To Our ONLINE MOVIE TICKET BOOKING SYSTEM (OMTBS)");
        LoginPanel.add(UserNoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 990, 40));

        UserForgetLabel.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        UserForgetLabel.setForeground(new java.awt.Color(255, 255, 0));
        UserForgetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserForgetLabel.setText("Forget Password");
        UserForgetLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserForgetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserForgetLabelMouseClicked(evt);
            }
        });
        LoginPanel.add(UserForgetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, 230, 40));

        PrivacyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Privacy_100px.png"))); // NOI18N
        PrivacyIcon.setToolTipText("Privacy");
        PrivacyIcon.setBorder(null);
        PrivacyIcon.setBorderPainted(false);
        PrivacyIcon.setContentAreaFilled(false);
        PrivacyIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        PrivacyIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Privacy_100px.png"))); // NOI18N
        LoginPanel.add(PrivacyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 100, 100));

        StayConnectWithUsLabel.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        StayConnectWithUsLabel.setForeground(new java.awt.Color(255, 0, 102));
        StayConnectWithUsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StayConnectWithUsLabel.setText("Stay Connect With Us");
        StayConnectWithUsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        StayConnectWithUsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StayConnectWithUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StayConnectWithUsLabelMousePressed(evt);
            }
        });
        LoginPanel.add(StayConnectWithUsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 740, 300, 40));

        SecurityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Security_100px.png"))); // NOI18N
        SecurityIcon.setToolTipText("Security");
        SecurityIcon.setBorder(null);
        SecurityIcon.setBorderPainted(false);
        SecurityIcon.setContentAreaFilled(false);
        SecurityIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        SecurityIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Security_100px.png"))); // NOI18N
        LoginPanel.add(SecurityIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 710, 90, -1));

        UserLoginBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallick_1230px.jpg"))); // NOI18N
        LoginPanel.add(UserLoginBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1230, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonIconMouseClicked

    private void MaximizeButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeButtonIconMouseClicked
        if(this.getExtendedState()!= Login.MAXIMIZED_BOTH){
        this.setExtendedState(Login.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Login.NORMAL);
        }
    }//GEN-LAST:event_MaximizeButtonIconMouseClicked

    private void MinimizeButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonIconMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonIconMouseClicked

    private void ShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordIconMousePressed
        HidePasswordIcon.setVisible(true);
        ShowPasswordIcon.setVisible(false);
        UserPasswordPassField.setEchoChar((char)0);
    }//GEN-LAST:event_ShowPasswordIconMousePressed

    private void HidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordIconMousePressed
        ShowPasswordIcon.setVisible(true);
        HidePasswordIcon.setVisible(false);
        UserPasswordPassField.setEchoChar('*');      
    }//GEN-LAST:event_HidePasswordIconMousePressed

    private void UserSignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserSignUpButtonMouseClicked
        Register reg = new Register();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_UserSignUpButtonMouseClicked

    private void UserSignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSignInButtonActionPerformed
        String uname = UserUserNameTextField.getText();
        String uemail = UserEmailIdTextField.getText();
        String upass = String.valueOf(UserPasswordPassField.getPassword());
        // boolean Checker = true;
        String uppolicy = "Not Agree";
        if(UserAgreeCheckBox.isSelected()){
           uppolicy = "Agree";
        }else{
           uppolicy = "Not Agree";
           Toolkit.getDefaultToolkit().beep();
           JOptionPane.showMessageDialog(null,"Please Agree To Our Privacy Policy, Otherwise You Can't Login" , "User Privacy Policy Message", JOptionPane.WARNING_MESSAGE);
        }
        
        if(uname.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Enter The Username" , "User Name Message", JOptionPane.WARNING_MESSAGE);
        }
        else if(uemail.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Enter The Email Address" , "User Emailid Message", JOptionPane.WARNING_MESSAGE);
        }
        else if(upass.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Enter The Password" , "User Password Message", JOptionPane.WARNING_MESSAGE);
        }
        else if(uppolicy.equals("Agree")){
            PreparedStatement ps;
            ResultSet rs;
            String UserLoginquery ="SELECT * FROM `user` WHERE `USER_NAME` = ? AND `USER_EMAILID` = ? AND `USER_PASSWORD` = ?";
            try{
                ps = MyConnection.getConnection().prepareStatement(UserLoginquery);
                ps.setString(1, uname);
                ps.setString(2, uemail);
                ps.setString(3, upass);
                rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"User Login Successfully" , "User Login Message", JOptionPane.INFORMATION_MESSAGE);
                    UserHome uh = new UserHome();
                    uh.setVisible(true);
                    uh.pack();
                    uh.UserHomeUserLabel.setText(uname);
                    uh.setLocationRelativeTo(null);
                    uh.setExtendedState(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
                else{
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null,"Login Failed! Incorrect Password or Username!" , "User Login Message", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            catch(SQLException ex){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,"Login Error" , "Login Error Message", JOptionPane.ERROR_MESSAGE);         
           }
        }
    }//GEN-LAST:event_UserSignInButtonActionPerformed

    private void UserForgetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserForgetLabelMouseClicked
        ForgetPassword fp = new ForgetPassword();
        fp.setVisible(true);
        fp.pack();
        fp.setLocationRelativeTo(null);
        fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_UserForgetLabelMouseClicked

    private void LoginSwitchUserIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSwitchUserIconMouseClicked
        AdminLogin aln = new AdminLogin();
        aln.setVisible(true);
        aln.pack();
        aln.setLocationRelativeTo(null);
        aln.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginSwitchUserIconMouseClicked

    private void StayConnectWithUsLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StayConnectWithUsLabelMousePressed
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new URI("http://localhost/OMTBS_RS/home.html"));  
            // file:///C:/xampp/htdocs/RABS_OEP/home.html
        } 
        catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"URL Redirection Failed" , "Redirection Error Message", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_StayConnectWithUsLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
       //Custome Joption UI
       //UIManager.put("OptionPane.background", Color.WHITE);
       //UIManager.put("OptionPane.foreground", Color.RED);  
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButtonIcon;
    private javax.swing.JLabel CompanyLogoIcon;
    private javax.swing.JLabel EmailIdName;
    private javax.swing.JButton HidePasswordIcon;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginSwitchUserIcon;
    private javax.swing.JButton MaximizeButtonIcon;
    private javax.swing.JButton MinimizeButtonIcon;
    private javax.swing.JButton PrivacyIcon;
    private javax.swing.JButton SecurityIcon;
    private javax.swing.JButton ShowPasswordIcon;
    private javax.swing.JLabel StayConnectWithUsLabel;
    private javax.swing.JCheckBox UserAgreeCheckBox;
    private javax.swing.JLabel UserEmailIdIcon;
    private javax.swing.JTextField UserEmailIdTextField;
    private javax.swing.JLabel UserForgetLabel;
    private javax.swing.JLabel UserLoginBgImg;
    private javax.swing.JLabel UserLoginFormLabel;
    private javax.swing.JLabel UserNoteLabel;
    private javax.swing.JLabel UserPasswordIcon;
    private javax.swing.JLabel UserPasswordLabel;
    private javax.swing.JPasswordField UserPasswordPassField;
    private javax.swing.JLabel UserPrivacyPolicyIcon;
    private javax.swing.JLabel UserPrivacyPolicyLabel;
    private javax.swing.JButton UserSignInButton;
    private javax.swing.JButton UserSignUpButton;
    private javax.swing.JLabel UserUserNameIcon;
    private javax.swing.JLabel UserUserNameLabel;
    public javax.swing.JTextField UserUserNameTextField;
    // End of variables declaration//GEN-END:variables
}
