package Omtbs;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.regex.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/* @author richu */

public class Register extends javax.swing.JFrame {

    /* Creates new form Register */
    public Register() {
        initComponents();
        this.HidePasswordIcon.setVisible(false);
        this.ConfirmHidePasswordIcon.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        RegisterPanel = new javax.swing.JPanel();
        CompanyLogo = new javax.swing.JLabel();
        UserRegisterFormLabel = new javax.swing.JLabel();
        CloseButtonIcon = new javax.swing.JButton();
        MinimizeButtonIcon = new javax.swing.JButton();
        MaximizeButtonIcon = new javax.swing.JButton();
        URUserNameLabel = new javax.swing.JLabel();
        UserRUsernameIcon = new javax.swing.JLabel();
        URUserNameTextField = new javax.swing.JTextField();
        URCommentUserName = new javax.swing.JLabel();
        UREmailIdLabel = new javax.swing.JLabel();
        UserREmailIdIcon = new javax.swing.JLabel();
        UREmailIdTextField = new javax.swing.JTextField();
        URCommentEmailId = new javax.swing.JLabel();
        URPasswordLabel = new javax.swing.JLabel();
        UserRpasswordIcon = new javax.swing.JLabel();
        URPasswordPassField = new javax.swing.JPasswordField();
        URCommentPassword = new javax.swing.JLabel();
        ShowPasswordIcon = new javax.swing.JButton();
        HidePasswordIcon = new javax.swing.JButton();
        URCPasswordLabel = new javax.swing.JLabel();
        UserRCPasswordIcon = new javax.swing.JLabel();
        URCPasswordPassField = new javax.swing.JPasswordField();
        ConfirmShowPasswordIcon = new javax.swing.JButton();
        ConfirmHidePasswordIcon = new javax.swing.JButton();
        URCommentConfirmPassword = new javax.swing.JLabel();
        URAddressLabel = new javax.swing.JLabel();
        UserRAddressIcon = new javax.swing.JLabel();
        URAddressScrollPanel = new javax.swing.JScrollPane();
        URAddressTextArea = new javax.swing.JTextArea();
        URCommentAddress = new javax.swing.JLabel();
        URMobileNoLabel = new javax.swing.JLabel();
        UserRMobileNoIcon = new javax.swing.JLabel();
        URMobileNoTextField = new javax.swing.JTextField();
        URCommentMobileNo = new javax.swing.JLabel();
        URGenderLabel = new javax.swing.JLabel();
        UserRGenderIcon = new javax.swing.JLabel();
        URMaleRadioButton = new javax.swing.JRadioButton();
        URFemaleRadioButton = new javax.swing.JRadioButton();
        URTransgenderRadioButton = new javax.swing.JRadioButton();
        URCommentGender = new javax.swing.JLabel();
        URDobLabel = new javax.swing.JLabel();
        UserRDobIcon = new javax.swing.JLabel();
        URtDobChooser = new com.toedter.calendar.JDateChooser();
        URCommentDob = new javax.swing.JLabel();
        URSubmitButton = new javax.swing.JButton();
        URResetButton = new javax.swing.JButton();
        URLoginButton = new javax.swing.JButton();
        URBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1355, 779));
        setName("UserRegistrationFrame"); // NOI18N
        setUndecorated(true);

        RegisterPanel.setBackground(new java.awt.Color(255, 204, 204));
        RegisterPanel.setMinimumSize(new java.awt.Dimension(1355, 779));
        RegisterPanel.setPreferredSize(new java.awt.Dimension(1355, 779));
        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompanyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/lightning _50px.png"))); // NOI18N
        CompanyLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterPanel.add(CompanyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        UserRegisterFormLabel.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        UserRegisterFormLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserRegisterFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRegisterFormLabel.setText("REGISTRATION FORM");
        UserRegisterFormLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterPanel.add(UserRegisterFormLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 470, -1));

        CloseButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseButtonIcon.setBorderPainted(false);
        CloseButtonIcon.setContentAreaFilled(false);
        CloseButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonIconMouseClicked(evt);
            }
        });
        RegisterPanel.add(CloseButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 50, 50));

        MinimizeButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MinimizeButtonIcon.setBorderPainted(false);
        MinimizeButtonIcon.setContentAreaFilled(false);
        MinimizeButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonIconMouseClicked(evt);
            }
        });
        RegisterPanel.add(MinimizeButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 50, 50));

        MaximizeButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeButtonIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MaximizeButtonIcon.setBorderPainted(false);
        MaximizeButtonIcon.setContentAreaFilled(false);
        MaximizeButtonIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaximizeButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeButtonIconMouseClicked(evt);
            }
        });
        RegisterPanel.add(MaximizeButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 50, 50));

        URUserNameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        URUserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URUserNameLabel.setText("USER NAME:");
        RegisterPanel.add(URUserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));

        UserRUsernameIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRUsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Contact_50px.png"))); // NOI18N
        RegisterPanel.add(UserRUsernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, 50));

        URUserNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        URUserNameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        URUserNameTextField.setForeground(new java.awt.Color(51, 51, 51));
        URUserNameTextField.setToolTipText("Enter your Full name");
        URUserNameTextField.setAutoscrolls(false);
        URUserNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URUserNameTextField.setMargin(new java.awt.Insets(4, 4, 4, 4));
        URUserNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                URUserNameTextFieldKeyReleased(evt);
            }
        });
        RegisterPanel.add(URUserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 370, 40));

        URCommentUserName.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentUserName.setForeground(new java.awt.Color(255, 51, 51));
        URCommentUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RegisterPanel.add(URCommentUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 360, 30));

        UREmailIdLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        UREmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        UREmailIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UREmailIdLabel.setText("EMAIL ID:");
        RegisterPanel.add(UREmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));

        UserREmailIdIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserREmailIdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Emailn_50px.png"))); // NOI18N
        RegisterPanel.add(UserREmailIdIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 50, 50));

        UREmailIdTextField.setBackground(new java.awt.Color(204, 204, 204));
        UREmailIdTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UREmailIdTextField.setAutoscrolls(false);
        UREmailIdTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        UREmailIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UREmailIdTextFieldKeyReleased(evt);
            }
        });
        RegisterPanel.add(UREmailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 390, 40));

        URCommentEmailId.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentEmailId.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 380, 30));

        URPasswordLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        URPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URPasswordLabel.setText("PASSWORD:");
        RegisterPanel.add(URPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, -1));

        UserRpasswordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRpasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/key_50px.png"))); // NOI18N
        RegisterPanel.add(UserRpasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, 50));

        URPasswordPassField.setBackground(new java.awt.Color(204, 204, 204));
        URPasswordPassField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        URPasswordPassField.setForeground(new java.awt.Color(51, 51, 51));
        URPasswordPassField.setToolTipText("Password must contain at least 8 characters and atmost 12 characters (Captial letters, Small letters, Numbers, Special Charcters @ ! #$ % & * - +)");
        URPasswordPassField.setAutoscrolls(false);
        URPasswordPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URPasswordPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                URPasswordPassFieldKeyReleased(evt);
            }
        });
        RegisterPanel.add(URPasswordPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 370, 40));

        URCommentPassword.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentPassword.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 360, 30));

        ShowPasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setToolTipText("Show Password");
        ShowPasswordIcon.setBorder(null);
        ShowPasswordIcon.setBorderPainted(false);
        ShowPasswordIcon.setContentAreaFilled(false);
        ShowPasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ShowPasswordIcon.setSelected(true);
        ShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowPasswordIconMousePressed(evt);
            }
        });
        RegisterPanel.add(ShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 40, 40));

        HidePasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        HidePasswordIcon.setToolTipText("Hide Password");
        HidePasswordIcon.setBorder(null);
        HidePasswordIcon.setBorderPainted(false);
        HidePasswordIcon.setContentAreaFilled(false);
        HidePasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HidePasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        HidePasswordIcon.setSelected(true);
        HidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HidePasswordIconMousePressed(evt);
            }
        });
        RegisterPanel.add(HidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 40, 40));

        URCPasswordLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URCPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        URCPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URCPasswordLabel.setText("CONFIRM PASSWORD:");
        RegisterPanel.add(URCPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 240, -1));

        UserRCPasswordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRCPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/key_50px.png"))); // NOI18N
        RegisterPanel.add(UserRCPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 50, 50));

        URCPasswordPassField.setBackground(new java.awt.Color(204, 204, 204));
        URCPasswordPassField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        URCPasswordPassField.setToolTipText("Password must contain at least 8 characters with (Captial letters, Small letters, Numbers, Special Charcters @ ! # $ % & * - + )");
        URCPasswordPassField.setAutoscrolls(false);
        URCPasswordPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URCPasswordPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                URCPasswordPassFieldKeyReleased(evt);
            }
        });
        RegisterPanel.add(URCPasswordPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 390, 40));

        ConfirmShowPasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConfirmShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmShowPasswordIcon.setToolTipText("Show Password");
        ConfirmShowPasswordIcon.setBorder(null);
        ConfirmShowPasswordIcon.setBorderPainted(false);
        ConfirmShowPasswordIcon.setContentAreaFilled(false);
        ConfirmShowPasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmShowPasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmShowPasswordIcon.setSelected(true);
        ConfirmShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmShowPasswordIconMousePressed(evt);
            }
        });
        RegisterPanel.add(ConfirmShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 280, 40, 40));

        ConfirmHidePasswordIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConfirmHidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Seen_40px.png"))); // NOI18N
        ConfirmHidePasswordIcon.setToolTipText("Hide Password");
        ConfirmHidePasswordIcon.setBorder(null);
        ConfirmHidePasswordIcon.setBorderPainted(false);
        ConfirmHidePasswordIcon.setContentAreaFilled(false);
        ConfirmHidePasswordIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmHidePasswordIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Eye_40px.png"))); // NOI18N
        ConfirmHidePasswordIcon.setSelected(true);
        ConfirmHidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmHidePasswordIconMousePressed(evt);
            }
        });
        RegisterPanel.add(ConfirmHidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 280, 40, 40));

        URCommentConfirmPassword.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentConfirmPassword.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 380, 30));

        URAddressLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        URAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URAddressLabel.setText("ADDRESS:");
        RegisterPanel.add(URAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        UserRAddressIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRAddressIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Addressmod_50px.png"))); // NOI18N
        RegisterPanel.add(UserRAddressIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 50, 50));

        URAddressTextArea.setBackground(new java.awt.Color(204, 204, 204));
        URAddressTextArea.setColumns(20);
        URAddressTextArea.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        URAddressTextArea.setRows(6);
        URAddressTextArea.setToolTipText("Enter Address in the format of (House name, Post office, Place, District, State, Country, Pincode)");
        URAddressTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URAddressTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                URAddressTextAreaKeyReleased(evt);
            }
        });
        URAddressScrollPanel.setViewportView(URAddressTextArea);

        RegisterPanel.add(URAddressScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 370, 200));

        URCommentAddress.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentAddress.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 360, 30));

        URMobileNoLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URMobileNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        URMobileNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URMobileNoLabel.setText("MOBILE NO:");
        RegisterPanel.add(URMobileNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 130, -1));

        UserRMobileNoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRMobileNoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/user-interface_50px.png"))); // NOI18N
        RegisterPanel.add(UserRMobileNoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 50, 50));

        URMobileNoTextField.setBackground(new java.awt.Color(204, 204, 204));
        URMobileNoTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        URMobileNoTextField.setToolTipText("");
        URMobileNoTextField.setAutoscrolls(false);
        URMobileNoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URMobileNoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                URMobileNoTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                URMobileNoTextFieldKeyTyped(evt);
            }
        });
        RegisterPanel.add(URMobileNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 390, 40));

        URCommentMobileNo.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentMobileNo.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 380, 30));

        URGenderLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        URGenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URGenderLabel.setText("GENDER:");
        RegisterPanel.add(URGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 100, 40));

        UserRGenderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRGenderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/SymbolGender_50px.png"))); // NOI18N
        RegisterPanel.add(UserRGenderIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 50, 50));

        GenderButtonGroup.add(URMaleRadioButton);
        URMaleRadioButton.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        URMaleRadioButton.setForeground(new java.awt.Color(255, 255, 51));
        URMaleRadioButton.setSelected(true);
        URMaleRadioButton.setText("Male");
        URMaleRadioButton.setContentAreaFilled(false);
        RegisterPanel.add(URMaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 80, 40));

        GenderButtonGroup.add(URFemaleRadioButton);
        URFemaleRadioButton.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        URFemaleRadioButton.setForeground(new java.awt.Color(255, 255, 0));
        URFemaleRadioButton.setText("Female");
        URFemaleRadioButton.setContentAreaFilled(false);
        RegisterPanel.add(URFemaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, -1, 40));

        GenderButtonGroup.add(URTransgenderRadioButton);
        URTransgenderRadioButton.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        URTransgenderRadioButton.setForeground(new java.awt.Color(255, 255, 0));
        URTransgenderRadioButton.setText("Transgender");
        URTransgenderRadioButton.setContentAreaFilled(false);
        RegisterPanel.add(URTransgenderRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 500, -1, 40));

        URCommentGender.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentGender.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 370, 30));

        URDobLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        URDobLabel.setForeground(new java.awt.Color(255, 255, 255));
        URDobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        URDobLabel.setText("DOB:");
        RegisterPanel.add(URDobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, -1, 40));

        UserRDobIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserRDobIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Birth_50px.png"))); // NOI18N
        RegisterPanel.add(UserRDobIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 50, 50));

        URtDobChooser.setBackground(new java.awt.Color(204, 204, 204));
        URtDobChooser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        URtDobChooser.setForeground(new java.awt.Color(255, 255, 255));
        URtDobChooser.setToolTipText("DD-MM-YYYY");
        URtDobChooser.setDateFormatString("dd-MM-y");
        URtDobChooser.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        RegisterPanel.add(URtDobChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, 320, 40));

        URCommentDob.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        URCommentDob.setForeground(new java.awt.Color(255, 51, 51));
        RegisterPanel.add(URCommentDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 390, 30));

        URSubmitButton.setBackground(new java.awt.Color(50, 150, 250));
        URSubmitButton.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        URSubmitButton.setText("Submit");
        URSubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        URSubmitButton.setBorderPainted(false);
        URSubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        URSubmitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        URSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URSubmitButtonActionPerformed(evt);
            }
        });
        RegisterPanel.add(URSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, 300, 50));

        URResetButton.setBackground(new java.awt.Color(255, 204, 255));
        URResetButton.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        URResetButton.setText("Reset");
        URResetButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        URResetButton.setBorderPainted(false);
        URResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        URResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URResetButtonActionPerformed(evt);
            }
        });
        RegisterPanel.add(URResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, 300, 50));

        URLoginButton.setBackground(new java.awt.Color(204, 255, 153));
        URLoginButton.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        URLoginButton.setText("Sign In");
        URLoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        URLoginButton.setBorderPainted(false);
        URLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        URLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                URLoginButtonMouseClicked(evt);
            }
        });
        RegisterPanel.add(URLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 720, 280, 50));

        URBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Techside_1390px.jpg"))); // NOI18N
        RegisterPanel.add(URBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1388, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonIconMouseClicked

    private void MinimizeButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonIconMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonIconMouseClicked
    
    private void ShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordIconMousePressed
        HidePasswordIcon.setVisible(true);
        ShowPasswordIcon.setVisible(false);
        URPasswordPassField.setEchoChar((char)0);
    }//GEN-LAST:event_ShowPasswordIconMousePressed

    private void HidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordIconMousePressed
        ShowPasswordIcon.setVisible(true);
        HidePasswordIcon.setVisible(false);
        URPasswordPassField.setEchoChar('*'); 
    }//GEN-LAST:event_HidePasswordIconMousePressed

    private void URLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_URLoginButtonMouseClicked
        Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_URLoginButtonMouseClicked

    private void URSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URSubmitButtonActionPerformed
        /*String urvalidatefname = URCommentUserName.getText();
        String urvalidateemail= URCommentEmailId.getText();
        String urvalidatepass = URCommentPassword.getText();
        String urvalidatecpass = URCommentConfirmPassword.getText();
        String urvalidateaddress = URCommentAddress.getText();
        String urvalidatemobile= URCommentMobileNo.getText();*/
        
        String uname = URUserNameTextField.getText();
        String uemail = UREmailIdTextField.getText();
        String upass = String.valueOf(URPasswordPassField.getPassword());
        String ucpass = String.valueOf(URCPasswordPassField.getPassword());
        String uaddress = URAddressTextArea.getText();
        String umobileno = URMobileNoTextField.getText();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String udob = dateformat.format(URtDobChooser.getDate());
        String ugender = "Male"; 
        if(URFemaleRadioButton.isSelected())
        {
            ugender = "Female";
        } 
        if(URTransgenderRadioButton.isSelected())
        {
            ugender = "Transgender";
        }    
        
        if(udob.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Enter The Date Of Birth" , "Date Of Birth", JOptionPane.WARNING_MESSAGE);
        }
        else if(uname.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter the Username" , "User Name", JOptionPane.WARNING_MESSAGE);
        }
        else if(uemail.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter your Email Address" , "Email Id", JOptionPane.WARNING_MESSAGE);
        }
        else if(upass.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter a password" , "Password", JOptionPane.WARNING_MESSAGE);
        }
        else if(!upass.equals(ucpass)){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Retype the Password Again" , "Confirm Password", JOptionPane.WARNING_MESSAGE);
        }
        else if(uaddress.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter your Address" , "Address", JOptionPane.WARNING_MESSAGE);
        }
        else if(umobileno.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter your Mobile no." , "Mobile No.", JOptionPane.WARNING_MESSAGE);
        }
        /*else if(urvalidatefname.equals("Naming is incorrect!") || urvalidateemail.equals("Email is incorrect!") 
                || !urvalidatepass.equals("Password Contain illegal characters") || !urvalidatecpass.equals("Password does not match!")
                || !urvalidateaddress.equals("Address is incorrect!") || !urvalidatemobile.equals("Mobile no is incorrect!")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Fill The Form In The Required Format" , "Required Format", JOptionPane.WARNING_MESSAGE);
        }  */          
        else if(!checkUsername(uname)){ 
            PreparedStatement ps;
            String RegisterUserQuery = "INSERT INTO `user`(`USER_NAME`, `USER_EMAILID`, `USER_PASSWORD`, `USER_MOBILE_NO`, `USER_DOB`, "
                    + "`USER_GENDER`, `USER_ADDRESS`) VALUES (?,?,?,?,?,?,?)";
            try{
                ps = MyConnection.getConnection().prepareStatement(RegisterUserQuery);
                ps.setString(1, uname);
                ps.setString(2, uemail);
                ps.setString(3, upass);
                ps.setString(4, umobileno);
                ps.setString(5, udob);
                ps.setString(6, ugender);
                ps.setString(7, uaddress);     
                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null,"User Account Has Been Successfully Created!" , "Welcome To Online Movie Ticket Booking System.", JOptionPane.INFORMATION_MESSAGE);
                    Login log = new Login();
                    log.setVisible(true);
                    log.pack();
                    log.setLocationRelativeTo(null);
                    log.setExtendedState(JFrame.EXIT_ON_CLOSE);
                    log.UserUserNameTextField.setText(uname);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"User Registration Failed!" , "User Registration", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            catch (SQLException ex) 
               {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null,"Registration Error Occuring!" , "Registration Error Message", JOptionPane.ERROR_MESSAGE);
               }
            }
        else{
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Code Bug" , "Bug", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_URSubmitButtonActionPerformed

    private void URUserNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URUserNameTextFieldKeyReleased
        String regex = "^[a-zA-Z ]{0,29}$";
        Pattern p = Pattern.compile(regex);
        Matcher match = p.matcher(URUserNameTextField.getText());
        if(!match.matches()){
            URCommentUserName.setText("Naming is incorrect!");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentUserName.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_URUserNameTextFieldKeyReleased

    private void UREmailIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UREmailIdTextFieldKeyReleased
        String regex = "^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z" + "A-Z]{2,7}$";
        Pattern p = Pattern.compile(regex);
        Matcher match = p.matcher(UREmailIdTextField.getText());
        if(!match.matches()){
            URCommentEmailId.setText("Email is incorrect!");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentEmailId.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_UREmailIdTextFieldKeyReleased

    private void URMobileNoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URMobileNoTextFieldKeyReleased
        String regex = "^[0-9]{0,12}$";
        Pattern p = Pattern.compile(regex);
        Matcher match = p.matcher(URMobileNoTextField.getText());
        if(!match.matches()){
            URCommentMobileNo.setText("Mobile no is incorrect!");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentMobileNo.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_URMobileNoTextFieldKeyReleased

    private void URAddressTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URAddressTextAreaKeyReleased
        String regex = "^[a-zA-Z0-9.,() ]{0,100}$";
        Pattern p = Pattern.compile(regex);
        Matcher match = p.matcher(URAddressTextArea.getText());
        if(!match.matches()){
            URCommentAddress.setText("Address is incorrect!");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentAddress.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_URAddressTextAreaKeyReleased

    private void URPasswordPassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URPasswordPassFieldKeyReleased
        String regex = "^[a-zA-Z0-9*-+@&#@/.?!]{1,12}$";
        Pattern p = Pattern.compile(regex);
        Matcher match = p.matcher(String.valueOf(URPasswordPassField.getPassword()));
        if(!match.matches()){
            URCommentPassword.setText("Password Contain illegal characters");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentPassword.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_URPasswordPassFieldKeyReleased

    private void URCPasswordPassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URCPasswordPassFieldKeyReleased
        String pass = String.valueOf(URPasswordPassField.getPassword());
        String cpass = String.valueOf(URCPasswordPassField.getPassword());
        if(cpass != null && ! cpass.equals(pass)){
            URCommentConfirmPassword.setText("Password does not match!");
            URSubmitButton.setEnabled(false);
        } 
        else{
            URCommentConfirmPassword.setText(null);
            URSubmitButton.setEnabled(true);
        }
    }//GEN-LAST:event_URCPasswordPassFieldKeyReleased

    private void ConfirmShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmShowPasswordIconMousePressed
        ConfirmHidePasswordIcon.setVisible(true);
        ConfirmShowPasswordIcon.setVisible(false);
        URCPasswordPassField.setEchoChar((char)0);
    }//GEN-LAST:event_ConfirmShowPasswordIconMousePressed

    private void ConfirmHidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmHidePasswordIconMousePressed
        ConfirmShowPasswordIcon.setVisible(true);
        ConfirmHidePasswordIcon.setVisible(false);
        URCPasswordPassField.setEchoChar('*'); 
    }//GEN-LAST:event_ConfirmHidePasswordIconMousePressed

    private void URMobileNoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_URMobileNoTextFieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
            URCommentMobileNo.setText("Numbers only");
        }
    }//GEN-LAST:event_URMobileNoTextFieldKeyTyped

    private void MaximizeButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeButtonIconMouseClicked
        if(this.getExtendedState()!= Register.MAXIMIZED_BOTH){
        this.setExtendedState(Register.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Register.NORMAL);
        }
    }//GEN-LAST:event_MaximizeButtonIconMouseClicked

    private void URResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URResetButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_URResetButtonActionPerformed
  
    public boolean checkUsername(String uname)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean username_exist = false; 
        try {
            String query = "SELECT * FROM `user` WHERE `USER_NAME` = ?";
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, uname);
            rs = ps.executeQuery();
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another one or Already Exist!", "Username Failed", 2);
            }   
        } 
        catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Existing User Checking Error!", "Checking Error Message", JOptionPane.ERROR_MESSAGE);
        }
        return username_exist;
    }
    
    public void clearFields(){
        URUserNameTextField.setText("");
        UREmailIdTextField.setText("");
        URPasswordPassField.setText("");
        URCPasswordPassField.setText("");
        URAddressTextArea.setText("");
        URMobileNoTextField.setText("");
        URtDobChooser.setDate(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButtonIcon;
    private javax.swing.JLabel CompanyLogo;
    private javax.swing.JButton ConfirmHidePasswordIcon;
    private javax.swing.JButton ConfirmShowPasswordIcon;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JButton HidePasswordIcon;
    private javax.swing.JButton MaximizeButtonIcon;
    private javax.swing.JButton MinimizeButtonIcon;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JButton ShowPasswordIcon;
    private javax.swing.JLabel URAddressLabel;
    private javax.swing.JScrollPane URAddressScrollPanel;
    private javax.swing.JTextArea URAddressTextArea;
    private javax.swing.JLabel URBgImg;
    private javax.swing.JLabel URCPasswordLabel;
    private javax.swing.JPasswordField URCPasswordPassField;
    private javax.swing.JLabel URCommentAddress;
    private javax.swing.JLabel URCommentConfirmPassword;
    private javax.swing.JLabel URCommentDob;
    private javax.swing.JLabel URCommentEmailId;
    private javax.swing.JLabel URCommentGender;
    private javax.swing.JLabel URCommentMobileNo;
    private javax.swing.JLabel URCommentPassword;
    private javax.swing.JLabel URCommentUserName;
    private javax.swing.JLabel URDobLabel;
    private javax.swing.JLabel UREmailIdLabel;
    private javax.swing.JTextField UREmailIdTextField;
    private javax.swing.JRadioButton URFemaleRadioButton;
    private javax.swing.JLabel URGenderLabel;
    private javax.swing.JButton URLoginButton;
    private javax.swing.JRadioButton URMaleRadioButton;
    private javax.swing.JLabel URMobileNoLabel;
    private javax.swing.JTextField URMobileNoTextField;
    private javax.swing.JLabel URPasswordLabel;
    private javax.swing.JPasswordField URPasswordPassField;
    private javax.swing.JButton URResetButton;
    private javax.swing.JButton URSubmitButton;
    private javax.swing.JRadioButton URTransgenderRadioButton;
    private javax.swing.JLabel URUserNameLabel;
    private javax.swing.JTextField URUserNameTextField;
    private com.toedter.calendar.JDateChooser URtDobChooser;
    private javax.swing.JLabel UserRAddressIcon;
    private javax.swing.JLabel UserRCPasswordIcon;
    private javax.swing.JLabel UserRDobIcon;
    private javax.swing.JLabel UserREmailIdIcon;
    private javax.swing.JLabel UserRGenderIcon;
    private javax.swing.JLabel UserRMobileNoIcon;
    private javax.swing.JLabel UserRUsernameIcon;
    private javax.swing.JLabel UserRegisterFormLabel;
    private javax.swing.JLabel UserRpasswordIcon;
    // End of variables declaration//GEN-END:variables
}
