package Omtbs;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/* @author richu */

public class UserHome extends javax.swing.JFrame {

    /* Creates new form UserHome */
    public UserHome() {
        initComponents();
        LoginUserFieldFetch();
        MoviesFieldFetch();
        bookingdetailsfetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserHomeMainPanel = new javax.swing.JPanel();
        UserHomeTopPanel = new javax.swing.JPanel();
        CloseIcon = new javax.swing.JLabel();
        MinimizeIcon = new javax.swing.JLabel();
        MaximizeIcon = new javax.swing.JLabel();
        UserHomeLogoutLabel = new javax.swing.JLabel();
        UserHomeMessageLabel = new javax.swing.JLabel();
        UserHomeUserLabel = new javax.swing.JLabel();
        UHRefreshIcon = new javax.swing.JLabel();
        TopPanelBgImg = new javax.swing.JLabel();
        UserHomeSidePanel = new javax.swing.JPanel();
        UserHomeFeedbackButton = new javax.swing.JButton();
        UserHomeProfileButton = new javax.swing.JButton();
        UserHomeMoviesButton = new javax.swing.JButton();
        UserHomeBookedButton = new javax.swing.JButton();
        UserHomeBookingButton = new javax.swing.JButton();
        UserHomeAboutButton = new javax.swing.JButton();
        SidePanelBgImg = new javax.swing.JLabel();
        UserHomeTabbedPane = new javax.swing.JTabbedPane();
        UserHomeProfilePanel = new javax.swing.JPanel();
        UHUsernameLabel = new javax.swing.JLabel();
        UHUsernameIcon = new javax.swing.JLabel();
        UHUsernameTextField = new javax.swing.JTextField();
        UHEmailidLabel = new javax.swing.JLabel();
        UHEmailidIcon = new javax.swing.JLabel();
        UHEmailidTextField = new javax.swing.JTextField();
        UHMobileNoLabel = new javax.swing.JLabel();
        UHMobileNoIcon = new javax.swing.JLabel();
        UHMobileNoTextField = new javax.swing.JTextField();
        UHDobLabel = new javax.swing.JLabel();
        UHDobIcon = new javax.swing.JLabel();
        UHDobTextField = new javax.swing.JTextField();
        UHGenderLabel = new javax.swing.JLabel();
        UHGenderIcon = new javax.swing.JLabel();
        UHGenderTextField = new javax.swing.JTextField();
        UHAddressLabel = new javax.swing.JLabel();
        UHAddressIcon = new javax.swing.JLabel();
        UHAddressScrollPane = new javax.swing.JScrollPane();
        UHAddressTextArea = new javax.swing.JTextArea();
        UHTimestampLabel = new javax.swing.JLabel();
        UHTimestampIcon = new javax.swing.JLabel();
        UHTimestampTextField = new javax.swing.JTextField();
        UHCalendar = new com.toedter.calendar.JCalendar();
        ProfileBgImg = new javax.swing.JLabel();
        UserHomeMoviesPanel = new javax.swing.JPanel();
        UHMovieLabel = new javax.swing.JLabel();
        UHMovieIcon = new javax.swing.JLabel();
        UHMovieTextField = new javax.swing.JTextField();
        UHMovieDescLabel = new javax.swing.JLabel();
        UHMovieDescIcon = new javax.swing.JLabel();
        UHMovieDescScrollPane = new javax.swing.JScrollPane();
        UHMovieDescTextArea = new javax.swing.JTextArea();
        UHMovieDetailsLabel = new javax.swing.JLabel();
        UHMovieDetailsIcon = new javax.swing.JLabel();
        UHMovieDetailsScrollPane = new javax.swing.JScrollPane();
        UHMovieDetailsTable = new javax.swing.JTable();
        MoviesBgImg = new javax.swing.JLabel();
        UserHomeBookedPanel = new javax.swing.JPanel();
        UHBookedScrollPane = new javax.swing.JScrollPane();
        UHBookedTable = new javax.swing.JTable();
        UHPintPreviewLabel = new javax.swing.JLabel();
        UHPrintScrollPane = new javax.swing.JScrollPane();
        UHPrintTextArea = new javax.swing.JTextArea();
        PrintButton = new javax.swing.JButton();
        UHPintPreviewIcon = new javax.swing.JLabel();
        BookedBgImg = new javax.swing.JLabel();
        UserHomeAboutPanel = new javax.swing.JPanel();
        AboutWhatsnewIcon = new javax.swing.JLabel();
        AboutWhatsnewLabel = new javax.swing.JLabel();
        AboutWhatsnewVersionLabel = new javax.swing.JLabel();
        WhatsnewN1Label = new javax.swing.JLabel();
        WhatsnewN2Label = new javax.swing.JLabel();
        WhatsnewN3Label = new javax.swing.JLabel();
        WhatsnewN4Label = new javax.swing.JLabel();
        WhatsnewN5Label = new javax.swing.JLabel();
        WhatsnewN6Label = new javax.swing.JLabel();
        AboutPreviousIcon = new javax.swing.JLabel();
        AboutPreviousLabel = new javax.swing.JLabel();
        AboutPreviousVersionLabel = new javax.swing.JLabel();
        PreviousP1Label = new javax.swing.JLabel();
        PreviousP2Label = new javax.swing.JLabel();
        PreviousP3Label = new javax.swing.JLabel();
        PreviousP4Label = new javax.swing.JLabel();
        PreviousP5Label = new javax.swing.JLabel();
        PreviousP6Label = new javax.swing.JLabel();
        PreviousP7Label = new javax.swing.JLabel();
        CheckForUpdateButton = new javax.swing.JButton();
        AboutBgImg = new javax.swing.JLabel();
        UserHomeFeedbackPanel = new javax.swing.JPanel();
        UserFeedbackLabel = new javax.swing.JLabel();
        UserFeedbackScrollPane = new javax.swing.JScrollPane();
        UserFeedbackTextArea = new javax.swing.JTextArea();
        UserContactLabel = new javax.swing.JLabel();
        WhatsappNoLabel = new javax.swing.JLabel();
        EmailIdLabel = new javax.swing.JLabel();
        UserFeedbackSubmitButton = new javax.swing.JButton();
        FeedbackBgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Home");
        setLocationByPlatform(true);
        setName("UserHomeFrame"); // NOI18N
        setUndecorated(true);

        UserHomeMainPanel.setBackground(new java.awt.Color(204, 255, 204));
        UserHomeMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserHomeTopPanel.setBackground(new java.awt.Color(102, 102, 255));
        UserHomeTopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Cross_50px.png"))); // NOI18N
        CloseIcon.setToolTipText("Close The Window");
        CloseIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseIconMouseClicked(evt);
            }
        });
        UserHomeTopPanel.add(CloseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 50, 50));

        MinimizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Minimize_50px.png"))); // NOI18N
        MinimizeIcon.setToolTipText("Minimize The Window");
        MinimizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeIconMouseClicked(evt);
            }
        });
        UserHomeTopPanel.add(MinimizeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 50, 50));

        MaximizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Maximize_50px.png"))); // NOI18N
        MaximizeIcon.setToolTipText("Maximize The Window");
        MaximizeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaximizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeIconMouseClicked(evt);
            }
        });
        UserHomeTopPanel.add(MaximizeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 50, -1));

        UserHomeLogoutLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        UserHomeLogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeLogoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/log-out_50px.png"))); // NOI18N
        UserHomeLogoutLabel.setText("Logout");
        UserHomeLogoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserHomeLogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserHomeLogoutLabelMouseClicked(evt);
            }
        });
        UserHomeTopPanel.add(UserHomeLogoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        UserHomeMessageLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        UserHomeMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeMessageLabel.setText("WELCOME:");
        UserHomeTopPanel.add(UserHomeMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 60));

        UserHomeUserLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UserHomeTopPanel.add(UserHomeUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 380, 60));

        UHRefreshIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Reload_50px.png"))); // NOI18N
        UHRefreshIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UHRefreshIconMouseClicked(evt);
            }
        });
        UserHomeTopPanel.add(UHRefreshIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        TopPanelBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Drew-beamer_1460px.jpg"))); // NOI18N
        UserHomeTopPanel.add(TopPanelBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 80));

        UserHomeMainPanel.add(UserHomeTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 80));

        UserHomeSidePanel.setBackground(new java.awt.Color(255, 255, 204));
        UserHomeSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserHomeFeedbackButton.setBackground(new java.awt.Color(0, 255, 204));
        UserHomeFeedbackButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeFeedbackButton.setText("Feedback");
        UserHomeFeedbackButton.setBorderPainted(false);
        UserHomeFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeFeedbackButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeFeedbackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 120, 40));

        UserHomeProfileButton.setBackground(new java.awt.Color(255, 102, 102));
        UserHomeProfileButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfileButton.setText("Profile");
        UserHomeProfileButton.setBorderPainted(false);
        UserHomeProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeProfileButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        UserHomeMoviesButton.setBackground(new java.awt.Color(255, 255, 51));
        UserHomeMoviesButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeMoviesButton.setText("Movies");
        UserHomeMoviesButton.setBorderPainted(false);
        UserHomeMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeMoviesButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeMoviesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 40));

        UserHomeBookedButton.setBackground(new java.awt.Color(255, 102, 255));
        UserHomeBookedButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeBookedButton.setText("Booked");
        UserHomeBookedButton.setBorderPainted(false);
        UserHomeBookedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeBookedButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeBookedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 40));

        UserHomeBookingButton.setBackground(new java.awt.Color(102, 102, 255));
        UserHomeBookingButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeBookingButton.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeBookingButton.setText("Booking");
        UserHomeBookingButton.setBorderPainted(false);
        UserHomeBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeBookingButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeBookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, 40));

        UserHomeAboutButton.setBackground(new java.awt.Color(102, 255, 102));
        UserHomeAboutButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeAboutButton.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeAboutButton.setText("About");
        UserHomeAboutButton.setBorderPainted(false);
        UserHomeAboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserHomeAboutButtonActionPerformed(evt);
            }
        });
        UserHomeSidePanel.add(UserHomeAboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 120, 40));

        SidePanelBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/william-daigneault_180px.jpg"))); // NOI18N
        UserHomeSidePanel.add(SidePanelBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 740));

        UserHomeMainPanel.add(UserHomeSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 740));

        UserHomeTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        UserHomeTabbedPane.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        UserHomeProfilePanel.setBackground(new java.awt.Color(204, 255, 255));
        UserHomeProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UHUsernameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHUsernameLabel.setText("USER NAME:");
        UserHomeProfilePanel.add(UHUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 110, 40));

        UHUsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/User_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHUsernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        UHUsernameTextField.setEditable(false);
        UHUsernameTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 330, 40));

        UHEmailidLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHEmailidLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHEmailidLabel.setText("EMAIL ID:");
        UserHomeProfilePanel.add(UHEmailidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 80, 40));

        UHEmailidIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Gmail_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHEmailidIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 50, 40));

        UHEmailidTextField.setEditable(false);
        UHEmailidTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHEmailidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 330, 40));

        UHMobileNoLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHMobileNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHMobileNoLabel.setText("MOBILE NO:");
        UserHomeProfilePanel.add(UHMobileNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 40));

        UHMobileNoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/user-interface_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHMobileNoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, 50));

        UHMobileNoTextField.setEditable(false);
        UHMobileNoTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHMobileNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 330, 40));

        UHDobLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHDobLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHDobLabel.setText("DATE OF BIRTH:");
        UserHomeProfilePanel.add(UHDobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 140, 40));

        UHDobIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Birth_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHDobIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 50, 50));

        UHDobTextField.setEditable(false);
        UHDobTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHDobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 270, 40));

        UHGenderLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHGenderLabel.setText("GENDER:");
        UserHomeProfilePanel.add(UHGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 80, 40));

        UHGenderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/SymbolGender_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHGenderIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, 50));

        UHGenderTextField.setEditable(false);
        UHGenderTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHGenderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 330, 40));

        UHAddressLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHAddressLabel.setText("ADDRESS:");
        UserHomeProfilePanel.add(UHAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 90, 30));

        UHAddressIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Addressmod_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHAddressIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 50, 50));

        UHAddressTextArea.setEditable(false);
        UHAddressTextArea.setColumns(20);
        UHAddressTextArea.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHAddressTextArea.setRows(5);
        UHAddressScrollPane.setViewportView(UHAddressTextArea);

        UserHomeProfilePanel.add(UHAddressScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 330, 150));

        UHTimestampLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHTimestampLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHTimestampLabel.setText("TIMESTAMP:");
        UserHomeProfilePanel.add(UHTimestampLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 110, 40));

        UHTimestampIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Chronometer_50px.png"))); // NOI18N
        UserHomeProfilePanel.add(UHTimestampIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 50, 50));

        UHTimestampTextField.setEditable(false);
        UHTimestampTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserHomeProfilePanel.add(UHTimestampTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 330, 40));

        UHCalendar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHCalendar.setNullDateButtonVisible(true);
        UHCalendar.setTodayButtonVisible(true);
        UserHomeProfilePanel.add(UHCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 530, 410));

        ProfileBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallickh_1280px.jpg"))); // NOI18N
        UserHomeProfilePanel.add(ProfileBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        UserHomeTabbedPane.addTab("Profile", UserHomeProfilePanel);

        UserHomeMoviesPanel.setBackground(new java.awt.Color(204, 204, 255));
        UserHomeMoviesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UHMovieLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHMovieLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHMovieLabel.setText("MOVIE:");
        UserHomeMoviesPanel.add(UHMovieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 70, 40));

        UHMovieIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/multimedia_50px.png"))); // NOI18N
        UserHomeMoviesPanel.add(UHMovieIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, 60));

        UHMovieTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UserHomeMoviesPanel.add(UHMovieTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 360, 40));

        UHMovieDescLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHMovieDescLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHMovieDescLabel.setText("MOVIE DESCRIPTION:");
        UserHomeMoviesPanel.add(UHMovieDescLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 180, 40));

        UHMovieDescIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/red-carpet_50px.png"))); // NOI18N
        UserHomeMoviesPanel.add(UHMovieDescIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 50, 50));

        UHMovieDescTextArea.setColumns(20);
        UHMovieDescTextArea.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        UHMovieDescTextArea.setRows(5);
        UHMovieDescScrollPane.setViewportView(UHMovieDescTextArea);

        UserHomeMoviesPanel.add(UHMovieDescScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 370, 320));

        UHMovieDetailsLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHMovieDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHMovieDetailsLabel.setText("MOVIE DETAILS:");
        UserHomeMoviesPanel.add(UHMovieDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, 40));

        UHMovieDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/movie_50px.png"))); // NOI18N
        UHMovieDetailsIcon.setText("jLabel2");
        UserHomeMoviesPanel.add(UHMovieDetailsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 50, 50));

        UHMovieDetailsTable.setAutoCreateRowSorter(true);
        UHMovieDetailsTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHMovieDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOVIE ID", "MOVIE NAME", "MOVIE DESCRIPTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        UHMovieDetailsTable.setRowHeight(20);
        UHMovieDetailsTable.setRowMargin(2);
        UHMovieDetailsTable.setShowGrid(false);
        UHMovieDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UHMovieDetailsTableMouseClicked(evt);
            }
        });
        UHMovieDetailsScrollPane.setViewportView(UHMovieDetailsTable);

        UserHomeMoviesPanel.add(UHMovieDetailsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 590, 620));

        MoviesBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallickh_1280px.jpg"))); // NOI18N
        MoviesBgImg.setText("jLabel7");
        UserHomeMoviesPanel.add(MoviesBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        UserHomeTabbedPane.addTab("Movies", UserHomeMoviesPanel);

        UserHomeBookedPanel.setBackground(new java.awt.Color(0, 255, 204));
        UserHomeBookedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UHBookedTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        UHBookedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USER", "MOVIE", "LANGUAGE", "LOCATION", "THEATHER", "TIME", "DATE", "NO. OF TICKET", "PRICE", "TOTAL", "STATUS", "SERIAL NO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        UHBookedTable.setCellSelectionEnabled(true);
        UHBookedTable.setInheritsPopupMenu(true);
        UHBookedTable.setShowGrid(true);
        UHBookedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UHBookedTableMouseClicked(evt);
            }
        });
        UHBookedScrollPane.setViewportView(UHBookedTable);

        UserHomeBookedPanel.add(UHBookedScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 620, 560));

        UHPintPreviewLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHPintPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        UHPintPreviewLabel.setText("PREVIEW:");
        UserHomeBookedPanel.add(UHPintPreviewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 130, 40));

        UHPrintTextArea.setEditable(false);
        UHPrintTextArea.setColumns(20);
        UHPrintTextArea.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        UHPrintTextArea.setRows(8);
        UHPrintTextArea.setTabSize(12);
        UHPrintTextArea.setBorder(null);
        UHPrintScrollPane.setViewportView(UHPrintTextArea);

        UserHomeBookedPanel.add(UHPrintScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 570, 630));

        PrintButton.setBackground(new java.awt.Color(0, 0, 255));
        PrintButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PrintButton.setForeground(new java.awt.Color(255, 255, 255));
        PrintButton.setText("Print");
        PrintButton.setBorder(null);
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        UserHomeBookedPanel.add(PrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 470, 50));

        UHPintPreviewIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UHPintPreviewIcon.setForeground(new java.awt.Color(255, 255, 255));
        UHPintPreviewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/loupe_50px.png"))); // NOI18N
        UserHomeBookedPanel.add(UHPintPreviewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 50));

        BookedBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallickh_1280px.jpg"))); // NOI18N
        UserHomeBookedPanel.add(BookedBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        UserHomeTabbedPane.addTab("Booked", UserHomeBookedPanel);

        UserHomeAboutPanel.setBackground(new java.awt.Color(255, 204, 204));
        UserHomeAboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutWhatsnewIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutWhatsnewIcon.setForeground(new java.awt.Color(255, 255, 255));
        AboutWhatsnewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/new_50px.png"))); // NOI18N
        UserHomeAboutPanel.add(AboutWhatsnewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 50));

        AboutWhatsnewLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutWhatsnewLabel.setForeground(new java.awt.Color(255, 255, 255));
        AboutWhatsnewLabel.setText("What's New:");
        UserHomeAboutPanel.add(AboutWhatsnewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 50));

        AboutWhatsnewVersionLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutWhatsnewVersionLabel.setForeground(new java.awt.Color(255, 255, 255));
        AboutWhatsnewVersionLabel.setText("VERSION 2.0.2      STABLE");
        UserHomeAboutPanel.add(AboutWhatsnewVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 270, 30));

        WhatsnewN1Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN1Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN1Label.setText("1.0 - New Redisigned UI (Fluid Metal)");
        UserHomeAboutPanel.add(WhatsnewN1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 420, 30));

        WhatsnewN2Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN2Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN2Label.setText("2.0 - Al improvement And Bug Fix");
        UserHomeAboutPanel.add(WhatsnewN2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 420, 30));

        WhatsnewN3Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN3Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN3Label.setText("3.0 - Security Improvement, Enhancement & Optimizations");
        UserHomeAboutPanel.add(WhatsnewN3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 570, 30));

        WhatsnewN4Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN4Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN4Label.setText("4.0 - Addition Of New User Interface for User, Admin, Superadmin");
        UserHomeAboutPanel.add(WhatsnewN4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 640, 30));

        WhatsnewN5Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN5Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN5Label.setText("5.0 - Decrease The Amout Of Resources Consumptions (CPU,GPU) So, 15% Faster Now When Compare To Previous Version ");
        UserHomeAboutPanel.add(WhatsnewN5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 1160, 30));

        WhatsnewN6Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        WhatsnewN6Label.setForeground(new java.awt.Color(255, 255, 255));
        WhatsnewN6Label.setText("6.0 - Font Enhancement (Style, Position, Size, Visibility)");
        UserHomeAboutPanel.add(WhatsnewN6Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 550, 30));

        AboutPreviousIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutPreviousIcon.setForeground(new java.awt.Color(255, 255, 255));
        AboutPreviousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/confetti_50px.png"))); // NOI18N
        UserHomeAboutPanel.add(AboutPreviousIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 50, 50));

        AboutPreviousLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutPreviousLabel.setForeground(new java.awt.Color(255, 255, 255));
        AboutPreviousLabel.setText("Previous Version:");
        UserHomeAboutPanel.add(AboutPreviousLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 170, 50));

        AboutPreviousVersionLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        AboutPreviousVersionLabel.setForeground(new java.awt.Color(255, 255, 255));
        AboutPreviousVersionLabel.setText("VERSION 1.0.1       BETA");
        UserHomeAboutPanel.add(AboutPreviousVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 250, 30));

        PreviousP1Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP1Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP1Label.setText("1.0 - New Beta UI (Slice Fluid)");
        UserHomeAboutPanel.add(PreviousP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 420, 30));

        PreviousP2Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP2Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP2Label.setText("2.0 - Random Crash Fix (Beta)");
        UserHomeAboutPanel.add(PreviousP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 420, 30));

        PreviousP3Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP3Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP3Label.setText("3.0 - Visibility Fix (Beta)");
        UserHomeAboutPanel.add(PreviousP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 420, 30));

        PreviousP4Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP4Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP4Label.setText("4.0 - Addition Of Encryption For Security");
        UserHomeAboutPanel.add(PreviousP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 420, 30));

        PreviousP5Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP5Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP5Label.setText("5.0 - Reduction In Resource Consumption (CPU, GPU) Beta");
        UserHomeAboutPanel.add(PreviousP5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 570, 30));

        PreviousP6Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP6Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP6Label.setText("6.0 - Updation Of Privacy Policy And Agreements");
        UserHomeAboutPanel.add(PreviousP6Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 490, 30));

        PreviousP7Label.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        PreviousP7Label.setForeground(new java.awt.Color(255, 255, 255));
        PreviousP7Label.setText("7.0 - Addition Of New Details About The System");
        UserHomeAboutPanel.add(PreviousP7Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 490, 30));

        CheckForUpdateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        CheckForUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckForUpdateButton.setText("Check for Updates");
        CheckForUpdateButton.setBorderPainted(false);
        CheckForUpdateButton.setContentAreaFilled(false);
        CheckForUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckForUpdateButtonActionPerformed(evt);
            }
        });
        UserHomeAboutPanel.add(CheckForUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 270, 40));

        AboutBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallickh_1280px.jpg"))); // NOI18N
        UserHomeAboutPanel.add(AboutBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        UserHomeTabbedPane.addTab("Version", UserHomeAboutPanel);

        UserHomeFeedbackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserFeedbackLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        UserFeedbackLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserFeedbackLabel.setText("FEEDBACK & REPORT:");
        UserHomeFeedbackPanel.add(UserFeedbackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 40));

        UserFeedbackTextArea.setColumns(20);
        UserFeedbackTextArea.setRows(5);
        UserFeedbackScrollPane.setViewportView(UserFeedbackTextArea);

        UserHomeFeedbackPanel.add(UserFeedbackScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 980, 360));

        UserContactLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        UserContactLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserContactLabel.setText("CONTACTS:");
        UserHomeFeedbackPanel.add(UserContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 40));

        WhatsappNoLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        WhatsappNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        WhatsappNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WhatsappNoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/whatsapp_30px.png"))); // NOI18N
        WhatsappNoLabel.setText("9856128589");
        WhatsappNoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WhatsappNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        UserHomeFeedbackPanel.add(WhatsappNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 200, 40));

        EmailIdLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Gmail_32px.png"))); // NOI18N
        EmailIdLabel.setText("omtbs1818@gmail.com");
        EmailIdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EmailIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        UserHomeFeedbackPanel.add(EmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 310, 40));

        UserFeedbackSubmitButton.setBackground(new java.awt.Color(255, 255, 0));
        UserFeedbackSubmitButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UserFeedbackSubmitButton.setText("SUBMIT");
        UserFeedbackSubmitButton.setBorderPainted(false);
        UserFeedbackSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFeedbackSubmitButtonActionPerformed(evt);
            }
        });
        UserHomeFeedbackPanel.add(UserFeedbackSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 210, 50));

        FeedbackBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OmtbsImages/Ray-mallickh_1280px.jpg"))); // NOI18N
        UserHomeFeedbackPanel.add(FeedbackBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        UserHomeTabbedPane.addTab("Feedback", UserHomeFeedbackPanel);

        UserHomeMainPanel.add(UserHomeTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 1280, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserHomeMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserHomeMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1460, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseIconMouseClicked

    private void MinimizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeIconMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeIconMouseClicked

    private void MaximizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeIconMouseClicked
        if(this.getExtendedState()!= UserHome.MAXIMIZED_BOTH){
            this.setExtendedState(UserHome.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(UserHome.NORMAL);
        }
    }//GEN-LAST:event_MaximizeIconMouseClicked

    private void UserHomeLogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserHomeLogoutLabelMouseClicked
        int option = JOptionPane.showConfirmDialog(UserHomeLogoutLabel,"Are You Sure Want to Logout", "Logout", JOptionPane.INFORMATION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            Login l = new Login();
            l.setVisible(true);
            l.pack();
            l.setLocationRelativeTo(null);
            l.setExtendedState(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }  
    }//GEN-LAST:event_UserHomeLogoutLabelMouseClicked

    private void UserHomeProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeProfileButtonActionPerformed
       UserHomeTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_UserHomeProfileButtonActionPerformed

    private void UserHomeMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeMoviesButtonActionPerformed
        UserHomeTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_UserHomeMoviesButtonActionPerformed

    private void UserHomeBookedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeBookedButtonActionPerformed
        UserHomeTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_UserHomeBookedButtonActionPerformed

    private void UserHomeBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeBookingButtonActionPerformed
        String suhu = UserHomeUserLabel.getText();
        //String suhu ="Richu Antony";
        MovieBooking mb = new MovieBooking();
        mb.setVisible(true);
        mb.pack();
        mb.setLocationRelativeTo(null);
        mb.UserNameTextField.setText(suhu);
    }//GEN-LAST:event_UserHomeBookingButtonActionPerformed

    private void UserHomeAboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeAboutButtonActionPerformed
        UserHomeTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_UserHomeAboutButtonActionPerformed

    private void UserHomeFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserHomeFeedbackButtonActionPerformed
       UserHomeTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_UserHomeFeedbackButtonActionPerformed

    private void UHRefreshIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UHRefreshIconMouseClicked
        LoginUserFieldFetch();
        MoviesFieldFetch();
        bookingdetailsfetch();
        UHPrintTextArea.setText("");
    }//GEN-LAST:event_UHRefreshIconMouseClicked

    private void UHMovieDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UHMovieDetailsTableMouseClicked
        DefaultTableModel Df = (DefaultTableModel)UHMovieDetailsTable.getModel();
        int selectedIndex = UHMovieDetailsTable.getSelectedRow();
        UHMovieTextField.setText(Df.getValueAt(selectedIndex, 1).toString());
        UHMovieDescTextArea.setText(Df.getValueAt(selectedIndex, 2).toString());
    }//GEN-LAST:event_UHMovieDetailsTableMouseClicked

    private void UHBookedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UHBookedTableMouseClicked
        String UHtimeStamp = new SimpleDateFormat("yyyy-MMM-dd   HH:mm:ss").format(new Date());
        DefaultTableModel Df = (DefaultTableModel)UHBookedTable.getModel();
        int selectedIndex = UHBookedTable.getSelectedRow();
        //Clear print Text pane
        UHPrintTextArea.setText("");
        //Header
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "**************************************************************************\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "***                 ONLINE MOVIE TICKET BOOKING SYSTEM                   ***\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "**************************************************************************\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "SERVICE PROVIDED BY: RA MOVIE BOOKING\n\n");
        //Content
        String puname = (String)(Df.getValueAt(selectedIndex, 1).toString());
        String pumovie= (String)(Df.getValueAt(selectedIndex, 2).toString());
        String pulan = (String)(Df.getValueAt(selectedIndex, 3).toString());
        String puloc = (String)(Df.getValueAt(selectedIndex, 4).toString());
        String putheather = (String)(Df.getValueAt(selectedIndex, 5).toString());
        String putime = (String)(Df.getValueAt(selectedIndex, 6).toString());
        String pudate = (String)(Df.getValueAt(selectedIndex, 7).toString());
        String puseat = (String)(Df.getValueAt(selectedIndex, 8).toString());
        String puprice = (String)(Df.getValueAt(selectedIndex, 9).toString());
        String putotal = (String)(Df.getValueAt(selectedIndex, 10).toString());
        String pustatus = (String)(Df.getValueAt(selectedIndex, 11).toString());
        String puserialno = (String)(Df.getValueAt(selectedIndex, 12).toString());
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "USER NAME: " + puname + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "CONFIRM USER NAME: " + puname + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "MOVIE NAME: " + pumovie + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "MOVIE LANGUAGE: " + pulan + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "THEATHER LOCATION: " + puloc + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "THEATHER NAME: " + putheather +"\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "SHOW TIME: " + putime + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "SHOW DATE: " + pudate +"\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "NO. OF SEATS: " + puseat +"\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "MOVIE TICKET PRICE: " + puprice +"\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "TOTAL AMOUNT: " + putotal + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "PAYED AMOUNT: " + putotal + "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "BOOK STATUS: " + pustatus +  "\n\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "BOOK STATUS: " + puserialno +  "\n\n");
        //Footer
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() +"                    THANK YOU HOPE YOU EXPRIENCE VERY WELL                  " + "\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "**************************************************************************\n");
        UHPrintTextArea.setText(UHPrintTextArea.getText() + "               " + puserialno +"             " + UHtimeStamp +"\n\n");
    }//GEN-LAST:event_UHBookedTableMouseClicked

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        try {
            UHPrintTextArea.print();
        }
        catch (PrinterException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Printing Error Occuring!", "Printing Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void UserFeedbackSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFeedbackSubmitButtonActionPerformed
        String feedbacksubmit = UserFeedbackTextArea.getText();
        String feedbackadmin = UserHomeUserLabel.getText();
        if(feedbacksubmit.equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please Enter The Feedback Before Submiting", "Feedback Submition", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                String FeedbacksubmitQuery = "INSERT INTO `feedback`(`FEEDBACK_USER`, `FEEDBACK`) VALUES (?,?)";
                PreparedStatement ps = MyConnection.getConnection().prepareStatement(FeedbacksubmitQuery);
                ps.setString(1, feedbackadmin);
                ps.setString(2, feedbacksubmit);
                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "Feedback Submitted Succesfully", "Feedback Submited", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Feedback Submition Failed!", "Feedback Failed", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Feedback Submition Error Occuring!", "Feedback Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_UserFeedbackSubmitButtonActionPerformed

    private void CheckForUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckForUpdateButtonActionPerformed
        try {
            Desktop d = Desktop.getDesktop();
            d.browse(new URI("http://localhost/OMTBS_RS/home.html"));  
            // file:///C:/xampp/htdocs/RABS_OEP/home.html
        } 
        catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"URL Redirection Failed" , "Redirection Error Message", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_CheckForUpdateButtonActionPerformed

    private void LoginUserFieldFetch(){
        try {
            String loginusername =  UserHomeUserLabel.getText();
            // String loginusername = "Richu Antony";
            String useradminfieldfetchquery ="SELECT `USER_NAME`, `USER_EMAILID`, `USER_MOBILE_NO`, `USER_DOB`, `USER_GENDER` , `USER_ADDRESS` , `USER_ACCOUNT_TIMESTAMP` FROM `user` WHERE `USER_NAME` = ? ";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(useradminfieldfetchquery);
            ps.setString(1, loginusername);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                UHUsernameTextField.setText(rs.getString(1));
                UHEmailidTextField.setText(rs.getString(2));
                UHMobileNoTextField.setText(rs.getString(3));
                UHDobTextField.setText(rs.getString(4));
                UHGenderTextField.setText(rs.getString(5));
                UHAddressTextArea.setText(rs.getString(6)); 
                UHTimestampTextField.setText(rs.getString(7));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Login User Details  Fetching Error Occuring!" , "User Details Fetching", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void MoviesFieldFetch(){
        int r;
        try {
            
            String moviefieldfetchquery ="SELECT *FROM `moviedetails`";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(moviefieldfetchquery);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            r = rsmd.getColumnCount();
            DefaultTableModel Dft = (DefaultTableModel)UHMovieDetailsTable.getModel();
            Dft.setRowCount(0);
            while(rs.next()){
                Vector vr2 = new Vector();
                for(int a=1; a<=r; a++){
                    vr2.add(rs.getString("MOVIE_ID"));
                    vr2.add(rs.getString("MOVIE_NAME"));
                    vr2.add(rs.getString("MOVIE_DESC"));
                }
                Dft.addRow(vr2);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Movies Filed Fetching Error Occuring!" , "Movies Fetching", JOptionPane.ERROR_MESSAGE);

        }
    }
    
    private void bookingdetailsfetch(){
        int r;
        try{
            PreparedStatement ps;
            String uuser = UserHomeUserLabel.getText();
            String bookedTableQuery = "SELECT * FROM `bookmovie` WHERE BOOK_USER = ?";
            ps = MyConnection.getConnection().prepareStatement(bookedTableQuery);
            ps.setString(1, uuser);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            r = rsmd.getColumnCount(); 
            DefaultTableModel Dft = (DefaultTableModel)UHBookedTable.getModel();
            Dft.setRowCount(0);
            while(rs.next()){
                Vector vr2 = new Vector();
                for(int a=1; a<=r; a++){
                    vr2.add(rs.getString("BOOK_ID"));
                    vr2.add(rs.getString("BOOK_USER"));
                    vr2.add(rs.getString("BOOK_MOVIE"));
                    vr2.add(rs.getString("BOOK_LANGUAGE"));
                    vr2.add(rs.getString("BOOK_LOCATION"));
                    vr2.add(rs.getString("BOOK_THEATHER"));
                    vr2.add(rs.getString("BOOK_TIME"));
                    vr2.add(rs.getString("BOOK_DATE"));
                    vr2.add(rs.getString("BOOK_SEATS"));
                    vr2.add(rs.getString("BOOK_PRICE"));
                    vr2.add(rs.getString("BOOK_TOTAL"));
                    vr2.add(rs.getString("BOOK_STATUS"));
                    vr2.add(rs.getString("BOOK_SERIALNO"));
                }
                Dft.addRow(vr2);
            }                        
        } 
        catch (SQLException ex){
            Logger.getLogger(BookConfirm.class.getName()).log(Level.SEVERE, null, ex);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"User Booking Tabel Data Collection Error Occuring!" , "User Booking Tabel Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutBgImg;
    private javax.swing.JLabel AboutPreviousIcon;
    private javax.swing.JLabel AboutPreviousLabel;
    private javax.swing.JLabel AboutPreviousVersionLabel;
    private javax.swing.JLabel AboutWhatsnewIcon;
    private javax.swing.JLabel AboutWhatsnewLabel;
    private javax.swing.JLabel AboutWhatsnewVersionLabel;
    private javax.swing.JLabel BookedBgImg;
    private javax.swing.JButton CheckForUpdateButton;
    private javax.swing.JLabel CloseIcon;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JLabel FeedbackBgImg;
    private javax.swing.JLabel MaximizeIcon;
    private javax.swing.JLabel MinimizeIcon;
    private javax.swing.JLabel MoviesBgImg;
    private javax.swing.JLabel PreviousP1Label;
    private javax.swing.JLabel PreviousP2Label;
    private javax.swing.JLabel PreviousP3Label;
    private javax.swing.JLabel PreviousP4Label;
    private javax.swing.JLabel PreviousP5Label;
    private javax.swing.JLabel PreviousP6Label;
    private javax.swing.JLabel PreviousP7Label;
    private javax.swing.JButton PrintButton;
    private javax.swing.JLabel ProfileBgImg;
    private javax.swing.JLabel SidePanelBgImg;
    private javax.swing.JLabel TopPanelBgImg;
    private javax.swing.JLabel UHAddressIcon;
    private javax.swing.JLabel UHAddressLabel;
    private javax.swing.JScrollPane UHAddressScrollPane;
    private javax.swing.JTextArea UHAddressTextArea;
    private javax.swing.JScrollPane UHBookedScrollPane;
    private javax.swing.JTable UHBookedTable;
    private com.toedter.calendar.JCalendar UHCalendar;
    private javax.swing.JLabel UHDobIcon;
    private javax.swing.JLabel UHDobLabel;
    private javax.swing.JTextField UHDobTextField;
    private javax.swing.JLabel UHEmailidIcon;
    private javax.swing.JLabel UHEmailidLabel;
    private javax.swing.JTextField UHEmailidTextField;
    private javax.swing.JLabel UHGenderIcon;
    private javax.swing.JLabel UHGenderLabel;
    private javax.swing.JTextField UHGenderTextField;
    private javax.swing.JLabel UHMobileNoIcon;
    private javax.swing.JLabel UHMobileNoLabel;
    private javax.swing.JTextField UHMobileNoTextField;
    private javax.swing.JLabel UHMovieDescIcon;
    private javax.swing.JLabel UHMovieDescLabel;
    private javax.swing.JScrollPane UHMovieDescScrollPane;
    private javax.swing.JTextArea UHMovieDescTextArea;
    private javax.swing.JLabel UHMovieDetailsIcon;
    private javax.swing.JLabel UHMovieDetailsLabel;
    private javax.swing.JScrollPane UHMovieDetailsScrollPane;
    private javax.swing.JTable UHMovieDetailsTable;
    private javax.swing.JLabel UHMovieIcon;
    private javax.swing.JLabel UHMovieLabel;
    private javax.swing.JTextField UHMovieTextField;
    private javax.swing.JLabel UHPintPreviewIcon;
    private javax.swing.JLabel UHPintPreviewLabel;
    private javax.swing.JScrollPane UHPrintScrollPane;
    private javax.swing.JTextArea UHPrintTextArea;
    private javax.swing.JLabel UHRefreshIcon;
    private javax.swing.JLabel UHTimestampIcon;
    private javax.swing.JLabel UHTimestampLabel;
    private javax.swing.JTextField UHTimestampTextField;
    private javax.swing.JLabel UHUsernameIcon;
    private javax.swing.JLabel UHUsernameLabel;
    private javax.swing.JTextField UHUsernameTextField;
    private javax.swing.JLabel UserContactLabel;
    private javax.swing.JLabel UserFeedbackLabel;
    private javax.swing.JScrollPane UserFeedbackScrollPane;
    private javax.swing.JButton UserFeedbackSubmitButton;
    private javax.swing.JTextArea UserFeedbackTextArea;
    private javax.swing.JButton UserHomeAboutButton;
    private javax.swing.JPanel UserHomeAboutPanel;
    private javax.swing.JButton UserHomeBookedButton;
    private javax.swing.JPanel UserHomeBookedPanel;
    private javax.swing.JButton UserHomeBookingButton;
    private javax.swing.JButton UserHomeFeedbackButton;
    private javax.swing.JPanel UserHomeFeedbackPanel;
    private javax.swing.JLabel UserHomeLogoutLabel;
    private javax.swing.JPanel UserHomeMainPanel;
    private javax.swing.JLabel UserHomeMessageLabel;
    private javax.swing.JButton UserHomeMoviesButton;
    private javax.swing.JPanel UserHomeMoviesPanel;
    private javax.swing.JButton UserHomeProfileButton;
    private javax.swing.JPanel UserHomeProfilePanel;
    private javax.swing.JPanel UserHomeSidePanel;
    private javax.swing.JTabbedPane UserHomeTabbedPane;
    private javax.swing.JPanel UserHomeTopPanel;
    public javax.swing.JLabel UserHomeUserLabel;
    private javax.swing.JLabel WhatsappNoLabel;
    private javax.swing.JLabel WhatsnewN1Label;
    private javax.swing.JLabel WhatsnewN2Label;
    private javax.swing.JLabel WhatsnewN3Label;
    private javax.swing.JLabel WhatsnewN4Label;
    private javax.swing.JLabel WhatsnewN5Label;
    private javax.swing.JLabel WhatsnewN6Label;
    // End of variables declaration//GEN-END:variables
}
